"""dashboard.json projection golden (CONTRACT §2 / §5 / §21 / §44.6 / §48 / §63 / §64).

Pins the FULL serialized output of ``dashboard.build_dashboard`` for a fixture
set that walks every lane branch of the projection — card_sent (with and
without cost / origin_trust / reraise), raising, detected, trashed (pinned,
purgeable, unparsable trashed_at), approved queued (concurrency-blocked and
plain), approved dispatch-halted, executing with a live pid / without one /
with an ISO started_at, review (idle / working / interrupted), delivered
(over COMPLETED_CAP ordering), merged / rejected / archived-in-active (all
invisible), a corrupt card (skipped, others survive), archived[] rows,
merge_suggestions job files (analyzing / done with groups / failed /
dismissed / corrupt / non-dict / bad groups), radar_sources with a stale
enabled source, §7 egress[] (repo-delivery card bootstrapping a missing dir
vs chat delivery), §10 capture_id (birth source row + proposal key), the §63 ``recaps[]``
top-level key (empty store) and the §64 ``assessment`` block (fresh on a
review card, stale-hash on a delivered card → omitted). Byte-for-byte: key ORDER inside every row is part of the wire
contract the Swift/web decoders were written against, so ``json.dumps`` with
``sort_keys=False`` is compared as text, not as a re-parsed dict.

The golden file lives at tests/fixtures/dashboard_golden.json. It was
generated by the pre-refactor v0.48.x projection (P3a); regenerate ONLY with
an intentional wire change in the same PR (``REGEN_DASHBOARD_GOLDEN=1``)
and say so in CONTRACT §2.
"""
import datetime as _dt
import json
import os
import tempfile
import unittest
from pathlib import Path
from unittest import mock

from tests import TMP_HOME  # noqa: F401 - sandbox env first

from act.lib import (card_summary, config, dashboard, deploy_state, fold_receipts,
                     radar_health, registry)
from act.lib.registry import Requirement

GOLDEN = Path(__file__).parent / "fixtures" / "dashboard_golden.json"
FIXED_NOW = "2026-09-02T12:00:00Z"
FIXED_TODAY = _dt.date(2026, 9, 2)


def _req(**kw) -> Requirement:
    return Requirement.from_dict(kw)


def _active_cards() -> list:
    cards = [
        _req(id="P-201", title="https://example.com/spec?q=1", status="card_sent",
             summary="给看板加导出按钮", tier="T1", hardness="hard",
             deadline="2026-09-10", repeated_mentions=3, silent_merge_count=2,
             cost_estimate_usd=4.5, green_sign_required=True,
             disagreement="有人想用 CSV", improvement_of="R-7",
             sources=[{"who": "alice", "channel": "quick", "date": "2026-09-01",
                       "quote": "能导出吗", "capture_id": "capture-0001"},
                      {"who": None, "channel": None, "date": None, "ref": "邮件引用"},
                      "not-a-dict"],
             plan="第一步\n第二步\n", outputs=["report.md"],
             definition_of_done=["能导出", "有测试"], delivery_mode="chat",
             execution={"reraised_at": "2026-09-01T00:00:00Z",
                        "reraised_note": "再来一次",
                        "auto_dispatch_block": "risk:T2"},
             origin_trust="external", work_id="R-201", user_titled=True,
             former_titles=["旧标题", " ", 42],
             notes="备注一行\n[radar] 并入 P-9 [@2026-09-01T00:00:00Z]"),
        _req(id="P-202", title="成本坏值卡", status="card_sent", tier="T0",
             cost_estimate_usd="cheap", repeated_mentions="abc",
             target_repo="~/definitely/not/here", execution="corrupt-string",
             plan=["a", "b"], deadline="not-a-date"),
        _req(id="P-203", title="研究中", status="raising", tier="T2",
             summary="", origin_trust="hand"),
        _req(id="P-204", title="潜在任务", status="detected", type="dev",
             hardness="soft", sources=[{"who": "bob", "channel": "gmail",
                                        "date": _dt.date(2026, 8, 30),
                                        "quote": "请看附件"}]),
        _req(id="P-205", title="回收站·可清", status="trashed",
             prev_status="detected", trashed_at="2026-08-01T10:00:00Z",
             trash_reason="stale", permanent=False, type="dev"),
        _req(id="P-206", title="回收站·钉住", status="trashed",
             prev_status="card_sent", trashed_at="2026-08-01T10:00:00+02:00",
             trash_reason="dup", permanent=True),
        _req(id="P-207", title="回收站·坏时间", status="trashed",
             prev_status="card_sent", trashed_at=1234567890,
             trash_reason=None),
        _req(id="P-208", title="回收站·裸时间", status="trashed",
             prev_status="card_sent", trashed_at="2026-08-01T10:00:00",
             trash_reason="x"),
        _req(id="R-210", title="排队·并发满", status="approved",
             summary="排队等", plan="步骤", definition_of_done=["done"],
             execution={"last_error": "claude: possibly due to low max file descriptors"}),
        _req(id="R-211", title="", status="approved"),
        _req(id="R-212", title="刹车卡", status="approved",
             execution={"dispatch_halted": True, "dispatch_attempts": 7,
                        "dispatch_class_streak": 5,
                        "last_error": "spawn failed: boom"},
             origin_trust="hand"),
        _req(id="R-213", title="刹车·无错误", status="approved",
             execution={"dispatch_halted": True}),
        _req(id="R-220", title="执行中·有 pid", status="executing",
             summary="干活", plan=["p1"], definition_of_done=["d1"],
             execution={"session_id": "c895e960", "log": "/tmp/R-220.log",
                        "dispatched_at": "2026-09-02T09:00:00Z",
                        "pending_briefings": ["x"],
                        "steers": [{"text": "先做 A", "ts": "2026-09-02T09:05:00Z",
                                    "status": "queued"}]},
             origin_trust="external"),
        _req(id="R-221", title="执行中·无 agent", status="executing",
             execution={"session_id": "deadbeef", "last_error": "resume failed"}),
        _req(id="R-222", title="执行中·无 session", status="executing",
             execution={}),
        _req(id="R-223", title="执行中·agent done", status="executing",
             execution={"session_id": "0badf00d",
                        "delivered_summary": "已完成", "final_draft": "稿" * 30,
                        "dispatched_at": 1756800000}),
        _req(id="R-230", title="待验收·闲", status="review",
             summary="概述", plan=["p"], sources=[{"who": "z", "channel": "quick",
                                                  "date": "2026-09-01", "quote": "q"}],
             execution={"session_id": "feedc0de", "log": "/tmp/l",
                        "dispatched_at": "2026-09-01T00:00:00Z",
                        "review_at": "2026-09-01T01:02:03Z",
                        "delivered_summary": "交付了", "final_draft": "x" * 20050,
                        "interrupted_reason": "blocked"}),
        _req(id="R-231", title="待验收·又在干", status="review",
             execution={"session_id": "12345678", "review_at": True}),
        _req(id="R-232", title="已验收·新", status="delivered",
             execution={"session_id": "cafe0001", "accepted_at": "2026-09-02T08:00:00Z",
                        "delivered_summary": "ok"}),
        _req(id="R-233", title="已验收·旧", status="delivered",
             execution={"accepted_at": "2026-01-01T00:00:00Z"}),
        _req(id="R-234", title="已验收·无时间", status="delivered", execution={}),
        _req(id="R-240", title="merged 不可见", status="merged"),
        _req(id="R-241", title="rejected 不可见", status="rejected"),
        _req(id="R-242", title="archived 残件", status="archived"),
        _req(id="R-243", title="merged_into 旧形", status="merged_into:R-201"),
        _req(id="R-250", title="crash-mid-move 残件", status="delivered",
             execution={"accepted_at": "2026-09-01T00:00:00Z"}),
    ]
    bad = _req(id="R-260", title="坏卡", status="card_sent")
    bad.definition_of_done = 42          # list(42) -> TypeError -> skipped
    cards.append(bad)
    by_id = {c.id: c for c in cards}
    # §64 assessment: fresh on the idle review card (projected), stale hash on
    # a delivered card (omitted — content moved on since the judge spoke)
    fresh = by_id["R-230"]
    fresh.assessment = {"summary": "交付了导出按钮", "verdict": "建议验收",
                        "verdict_reason": "DoD 两条都有证据", "at": "2026-09-02T10:00:00Z",
                        "source_hash": card_summary.source_hash(fresh)}
    by_id["R-232"].assessment = {"summary": "旧话", "verdict": "需继续做",
                                 "at": "2026-09-01T00:00:00Z", "source_hash": "stale"}
    return cards


def _archived_cards() -> list:
    return [
        _req(id="R-250", title="归档·新", status="archived", prev_status="delivered",
             archived_at="2026-08-20T00:00:00Z", archive_reason="stale", type="dev"),
        _req(id="R-251", title="归档·debt", status="archived", prev_status="detected",
             archived_at="2026-08-10T00:00:00Z", archive_reason="old"),
        _req(id="R-252", title="归档·无时间", status="archived"),
    ]


def _agents() -> list:
    return [
        {"id": "c895e960", "sessionId": "c895e960-1111-2222-3333-444444444444",
         "pid": 4242, "cwd": "/tmp/wt-220", "name": "huge prompt", "state": "WORKING",
         "started_at": "2026-09-02T09:01:00Z"},
        {"id": "0badf00d", "sessionId": "0badf00d-1111-2222-3333-444444444444",
         "state": "done", "startedAt": 1756800100, "cwd": "/tmp/wt-223"},
        {"id": "12345678", "sessionId": "12345678-aaaa-2222-3333-444444444444",
         "pid": 7, "state": "running", "started_at": "bogus"},
        "not-a-dict",
        {"name": "no ids at all", "state": "idle"},
    ]


def _write_merge_jobs(d: Path) -> None:
    d.mkdir(parents=True, exist_ok=True)
    jobs = {
        "MS-00000001": {"id": "MS-00000001", "ids": ["P-201", "P-202"],
                        "status": "analyzing",
                        "requested_at": "2026-09-02T10:00:00Z"},
        "MS-00000002": {"id": "MS-00000002", "ids": ["P-203", 204, "P-205"],
                        "status": "done", "verdict": "partition",
                        "primary": "P-203", "rationale": "两件事",
                        "action_plan": ["并 A", 2], "confidence": "high",
                        "requested_at": "2026-09-02T11:00:00Z",
                        "expires_at": "2026-09-03T11:00:00Z",
                        "groups": [{"primary": "P-203", "ids": ["P-203", 204],
                                    "reason": "同一件事"},
                                   {"primary": None, "ids": "bad", "reason": ""},
                                   "not-a-dict"]},
        "MS-00000003": {"status": "FAILED", "ids": "not-a-list",
                        "error": "claude -p exited 1", "action_plan": "not-a-list",
                        "requested_at": "not-a-date", "groups": []},
        "MS-00000004": {"id": "MS-00000004", "status": "dismissed", "ids": ["a"]},
        "MS-00000005": {"id": "MS-00000005", "status": "done", "ids": ["a", "b"],
                        "requested_at": "2026-09-02T09:00:00Z", "groups": "nope"},
    }
    for name, job in jobs.items():
        (d / f"{name}.json").write_text(json.dumps(job), encoding="utf-8")
    (d / "MS-corrupt.json").write_text("{not json", encoding="utf-8")
    (d / "MS-list.json").write_text("[1, 2]", encoding="utf-8")


def _radar_health() -> dict:
    return {
        "gmail": {"last_attempt": "2020-01-01T00:00:00Z",
                  "last_ok": "2020-01-01T00:00:00Z", "skip_reason": None},
        "slack": {"last_ok": "", "skip_reason": "mcp_failed: boom /Users/x"},
        "obsidian": "not-a-dict",
    }


class GoldenCfg(config.Config):
    """Every radar source enabled so radar_sources shows the stale/skip path."""

    def feature(self, name):  # noqa: D401 - test double
        return True


def _receipts() -> list:
    return [{"req": "R-220", "channel": "radar", "at": 1756800000},
            {"req": "R-gone", "channel": "capture", "at": 1756800001}]


def _registry_load(card_id: str):
    if card_id == "R-220":
        return _req(id="R-220", title="执行中·有 pid", status="executing",
                    display_title="显示名 R-220")
    return None


def build_fixture_dashboard(merge_dir: Path, state_dir: Path) -> dict:
    cfg = GoldenCfg()
    cfg.gmail_enabled = True
    cfg.slack_enabled = True
    cfg.obsidian_enabled = True
    cfg.show_cost_above_usd = 1.0
    cfg.trash_retention_days = 30
    cfg.default_target_repo = "/golden/workbench"   # no $HOME leak into the golden
    cfg.create_github_repo = True                   # §7 egress[] disclosure path
    _write_merge_jobs(merge_dir)
    state_dir.mkdir(parents=True, exist_ok=True)
    (state_dir / "sync.json").write_text(json.dumps({"label": " Zelin 的 Mac "}),
                                         encoding="utf-8")
    # every disk-backed side input is pinned: the suite's shared sandbox
    # STATE_DIR accumulates fold receipts / deploy state from other tests
    with mock.patch.object(dashboard, "_iso_now", return_value=FIXED_NOW), \
            mock.patch.object(dashboard, "_today", return_value=FIXED_TODAY), \
            mock.patch.object(dashboard.config, "load_config", return_value=cfg), \
            mock.patch.object(dashboard.config, "STATE_DIR", state_dir), \
            mock.patch.object(radar_health, "load_radar_health",
                              return_value=_radar_health()), \
            mock.patch.object(fold_receipts, "load_recent",
                              side_effect=_receipts), \
            mock.patch.object(registry, "load", side_effect=_registry_load), \
            mock.patch.object(deploy_state, "read",
                              return_value={"version": "0.48.99",
                                            "status": "deployed"}), \
            mock.patch.object(dashboard, "COMPLETED_CAP", 2), \
            mock.patch.object(dashboard, "ARCHIVED_CAP", 2):
        return dashboard.build_dashboard(
            reqs=_active_cards(), agents=_agents(), cfg=cfg,
            merge_dir=merge_dir, archived=_archived_cards())


def serialize(dash: dict) -> str:
    return json.dumps(dash, ensure_ascii=False, indent=2,
                      default=dashboard._json_default) + "\n"


class DashboardGoldenTestCase(unittest.TestCase):
    def setUp(self):
        home = tempfile.mkdtemp(prefix="dash-golden-home-")
        patcher = mock.patch.dict(os.environ, {"HOME": home})
        patcher.start()
        self.addCleanup(patcher.stop)
        self.merge_dir = Path(tempfile.mkdtemp(prefix="dash-golden-merge-"))
        self.state_dir = Path(tempfile.mkdtemp(prefix="dash-golden-state-"))

    def test_projection_matches_golden_byte_for_byte(self):
        import io
        import contextlib
        err = io.StringIO()
        with contextlib.redirect_stderr(err):
            text = serialize(build_fixture_dashboard(self.merge_dir, self.state_dir))
        # the corrupt card is skipped with a stderr line, everything else lands
        self.assertIn("skip corrupt card 'R-260'", err.getvalue())
        if os.environ.get("REGEN_DASHBOARD_GOLDEN") == "1":
            GOLDEN.parent.mkdir(parents=True, exist_ok=True)
            GOLDEN.write_text(text, encoding="utf-8")
        self.assertTrue(GOLDEN.exists(), "golden missing — REGEN_DASHBOARD_GOLDEN=1 to mint")
        self.assertEqual(text, GOLDEN.read_text(encoding="utf-8"))

    def test_golden_covers_every_partition(self):
        """Sanity: the fixture really exercises each lane (a hollow golden
        would pass the byte comparison while pinning nothing)."""
        dash = json.loads(GOLDEN.read_text(encoding="utf-8"))
        for key in ("needs_approval", "running", "needs_input", "review",
                    "completed", "debt", "trash", "archived", "merge_suggestions"):
            self.assertTrue(dash[key], key)
        self.assertEqual(dash["counts"]["completed"], 3)      # TRUE total, cap 2
        self.assertEqual(len(dash["completed"]), 2)
        self.assertEqual(dash["counts"]["archived"], 3)
        self.assertEqual(len(dash["archived"]), 2)
        states = {r["state"] for r in dash["running"]}
        self.assertTrue({"queued", "working", "unknown"} <= states, states)
        self.assertTrue(any(r.get("from_review") for r in dash["running"]))
        self.assertTrue(dash["radar_sources"]["gmail"]["stale"])
        self.assertEqual(dash["radar_sources"]["slack"]["skip_reason"], "mcp_failed")
        self.assertEqual([r["title"] for r in dash["fold_receipts"]], ["显示名 R-220", ""])
        self.assertEqual(dash["device_label"], "Zelin 的 Mac")
        self.assertEqual(dash["deploy_state"]["version"], "0.48.99")
        self.assertEqual(dash["recaps"], [])
        review = {r["id"]: r for r in dash["review"]}
        self.assertEqual(review["R-230"]["assessment"]["verdict"], "建议验收")
        self.assertTrue(all("assessment" not in r for r in dash["completed"]))
        by_id = {r["id"]: r for r in dash["needs_approval"]}
        self.assertEqual(by_id["P-201"]["egress"], [])                 # chat delivery
        self.assertEqual(by_id["P-202"]["egress"][0]["kind"], "github_repo_create")
        self.assertEqual(by_id["P-201"]["capture_id"], "capture-0001")
        self.assertEqual(by_id["P-201"]["sources"][0]["capture_id"], "capture-0001")
        self.assertNotIn("capture_id", by_id["P-202"])


if __name__ == "__main__":
    unittest.main()
