// Render stage engine. Builds a faithful DOM replica of the app's kanban from
// demo_seed scene JSON (window.SCENES, generated by prepare.sh) and exposes
// window.seek(t): a PURE function of time — every style it touches is set on
// every call, so frames are deterministic and the capture can scrub anywhere.

/* eslint-disable no-unused-vars */
'use strict';

const $ = (sel) => document.querySelector(sel);
const clamp01 = (v) => Math.max(0, Math.min(1, v));
const lerp = (a, b, p) => a + (b - a) * p;
const seg = (t, a, b) => clamp01((t - a) / Math.max(1e-6, b - a));
const easeIO = (p) => (p < 0.5 ? 4 * p * p * p : 1 - Math.pow(-2 * p + 2, 3) / 2);
const easeOut = (p) => 1 - Math.pow(1 - p, 4);
const easeOutBack = (p) => {
  const c = 2.0;
  return 1 + (c + 1) * Math.pow(p - 1, 3) + c * Math.pow(p - 1, 2);
};

const PANE_ORDER = ['captured', 'initial', 'approved', 'running', 'review', 'done'];
const HERO = 'R-101';

// ------------------------------------------------------------------ helpers
function el(tag, cls, text) {
  const e = document.createElement(tag);
  if (cls) e.className = cls;
  if (text != null) e.textContent = text;
  return e;
}

function splitWords(container, text) {
  // one span per CJK char / latin word, so captions can stagger in
  const parts = text.match(/[A-Za-z0-9$#@._\-—:：]+|\s+|./gu) || [];
  for (const p of parts) {
    const w = el('span', 'w', p);
    container.appendChild(w);
  }
  return container;
}

function isoToEpoch(s) { return Math.floor(Date.parse(s) / 1000); }

const EN = () => window.LANG === 'en';

// time strings mirror the app's real L() pairs in Cards.swift
function agoStr(nowE, e) {
  const m = Math.round((nowE - e) / 60);
  if (m < 1) return EN() ? 'just now' : '刚刚';
  if (m < 60) return EN() ? `${m}m ago` : `${m}分钟前`;
  const h = Math.round(m / 60);
  if (h < 24) return EN() ? `${h}h ago` : `${h}小时前`;
  const d = Math.round(h / 24);
  return EN() ? `${d}d ago` : `${d}天前`;
}

function durStr(sec) {
  if (sec < 60) { const s = Math.max(1, Math.round(sec)); return EN() ? `${s}s` : `${s}秒`; }
  const m = Math.round(sec / 60);
  if (m < 60) return EN() ? `${m}m` : `${m}分钟`;
  const h = Math.round(m / 6) / 10;
  return EN() ? `${h}h` : `${h}小时`;
}

function repoName(p) { return (p || '').split('/').pop(); }

// -------------------------------------------------------------- card DOM
function chipsFor(c) {
  const box = el('div', 'chips cascade');
  box.appendChild(el('span', 'chip tier', T(`${c.tier} · ${c.tier_hint}`)));
  if (c.delivery_mode === 'chat') box.appendChild(el('span', 'chip chat', T('交付：聊天成稿')));
  if (c.deadline) box.appendChild(el('span', 'chip deadline',
    EN() ? `Due ${c.deadline} (${c.days_left}d)` : `截止 ${c.deadline} (${c.days_left}d)`));
  if (c.hardness) box.appendChild(el('span', `chip ${c.hardness === 'hard' ? 'hard' : ''}`, c.hardness));
  if (c.show_cost && c.cost_usd != null) box.appendChild(el('span', 'chip cost', `$${c.cost_usd}`));
  if (c.repeated > 1) box.appendChild(el('span', 'chip',
    EN() ? `Repeated ×${c.repeated}` : `重复 ×${c.repeated}`));
  if (c.green_sign) box.appendChild(el('span', 'chip gsign', T('需 manager green-sign（只出草稿）')));
  return box;
}

function naCard(c) {
  if (c.processing) {
    const card = el('div', 'card processing');
    card.appendChild(el('div', 'spinner'));
    const body = el('div');
    body.appendChild(el('div', 'title', T(c.title)));
    body.appendChild(el('div', 'sub', T('AI 研究中…（补全上下文、生成提案）')));
    card.appendChild(body);
    if (c.id === HERO) card.classList.add('hero');
    return card;
  }
  const card = el('div', 'card');
  card.appendChild(el('div', 'title', T(c.title)));
  const kind = c.target_kind === 'new'
    ? (EN() ? `🟢 New repo: ${c.target_name}` : `🟢 新建 repo: ${c.target_name}`)
    : (EN() ? `🟠 Modify existing: ${c.target_name}` : `🟠 修改现有: ${c.target_name}`);
  const meta = el('div', `metaline cascade ${c.target_kind === 'new' ? 'new' : ''}`);
  meta.textContent = kind;
  if (c.delivery_mode === 'repo') {
    const d = el('span', 'dim', EN()
      ? ' (draft PR only, main branch untouched)' : '（只提 draft PR，不动主分支）');
    meta.appendChild(d);
  }
  card.appendChild(meta);
  card.appendChild(chipsFor(c));
  if (c.dod && c.dod.length) {
    card.appendChild(el('div', 'dodhead cascade', T('怎样算办完：')));
    const list = el('div', 'dodlist');
    c.dod.forEach((d, i) => list.appendChild(el('div', 'li cascade', `${i + 1}. ${T(d)}`)));
    card.appendChild(list);
  }
  if (c.disagreement) card.appendChild(el('div', 'disagree cascade',
    (EN() ? '⚠︎ Disagreement: ' : '⚠ 分歧: ') + T(c.disagreement)));
  const row = el('div', 'btnrow cascade');
  row.appendChild(el('div', 'btn approve', T('✓ 批准')));
  row.appendChild(el('div', 'btn reject', T('✕ 拒绝')));
  row.appendChild(el('div', 'btn', T('💬 修改')));
  row.appendChild(el('div', 'btn ghost', T('展开详情 ▸')));
  card.appendChild(row);
  if (c.id === HERO) card.classList.add('hero');
  return card;
}

function runCard(r, nowE) {
  const card = el('div', 'card');
  const row = el('div', 'namerow');
  const blocked = r.state === 'blocked';
  const queued = r.state === 'queued';
  row.appendChild(el('div', `dot ${blocked ? 'orange' : queued ? 'gray' : 'blue'}`));
  const body = el('div');
  body.appendChild(el('div', 'title', T(r.name)));
  const badges = el('div', 'chips');
  if (blocked) {
    badges.appendChild(el('span', 'badge input', T('需输入')));
    badges.appendChild(el('span', 'badge blocked', 'blocked'));
    badges.appendChild(el('span', 'badge', r.short_id));
  } else if (queued) {
    badges.appendChild(el('span', 'badge queued', T('排队中')));
  } else {
    badges.appendChild(el('span', 'badge working', 'working'));
    badges.appendChild(el('span', 'badge', r.short_id));
    if (r.started_at) badges.appendChild(el('span', 'badge', agoStr(nowE, r.started_at)));
    if (r.cwd) badges.appendChild(el('span', 'badge', repoName(r.cwd)));
  }
  body.appendChild(badges);
  const copyLabel = EN() ? 'Click to copy · double-click runs: ' : '单击复制 · 双击在终端运行：';
  if (blocked) body.appendChild(el('div', 'mono',
    `${EN() ? 'Waiting: ' : '等待: '}${r.waiting_for} · ${copyLabel}${r.copy_cmd}`));
  else if (!queued) {
    body.appendChild(el('div', 'mono', `${copyLabel}${r.copy_cmd}`));
    body.appendChild(el('div', 'mono',
      `${EN() ? 'claude agents list name: ' : 'claude agents 列表名: '}${r.agent_name}`));
  }
  if (r.last_error) body.appendChild(el('div', 'errline',
    `${EN() ? 'Error: ' : '错误: '}${r.last_error}`));
  const btns = el('div', 'btnrow');
  btns.appendChild(el('div', 'btn', T('◉ 停止')));
  if (!queued && !blocked) btns.appendChild(el('div', 'btn ghost', T('展开详情 ▸')));
  body.appendChild(btns);
  row.appendChild(body);
  card.appendChild(row);
  if (r.id === HERO) card.classList.add('hero');
  return card;
}

function reviewCard(r, nowE) {
  const card = el('div', 'card');
  const row = el('div', 'namerow');
  row.appendChild(el('div', 'dot blue'));
  const body = el('div');
  body.appendChild(el('div', 'title', T(r.name)));
  const dl = el('div', 'delivered');
  const bold = el('b', null, T('交付了什么：'));
  dl.appendChild(bold);
  dl.appendChild(document.createTextNode(T(r.delivered_summary)));
  body.appendChild(dl);
  body.appendChild(el('div', 'dodhead', T('验收清单——逐条对照：')));
  const list = el('div', 'dodlist');
  (r.dod || []).forEach((d) => {
    const it = el('div', 'checkitem');
    it.appendChild(el('span', 'box', '☐'));
    it.appendChild(el('span', null, T(d)));
    list.appendChild(it);
  });
  body.appendChild(list);
  const badges = el('div', 'chips');
  if (r.cwd) badges.appendChild(el('span', 'badge', repoName(r.cwd)));
  badges.appendChild(el('span', 'badge',
    `${EN() ? 'took ' : '耗时 '}${durStr(r.review_at - r.dispatched_at)}`));
  badges.appendChild(el('span', 'badge',
    `${EN() ? 'in review ' : '已等待验收 '}${durStr(nowE - r.review_at)}`));
  body.appendChild(badges);
  body.appendChild(el('div', 'mono',
    `${EN() ? 'Click to copy · double-click runs: ' : '单击复制 · 双击在终端运行：'}${r.copy_cmd}`));
  const btns = el('div', 'btnrow');
  btns.appendChild(el('div', 'btn accept', T('✓ 验收')));
  btns.appendChild(el('div', 'btn', T('↩ 打回')));
  if (r.delivery_mode === 'chat') btns.appendChild(el('div', 'btn', T('📋 复制成稿')));
  body.appendChild(btns);
  row.appendChild(body);
  card.appendChild(row);
  if (r.id === HERO) card.classList.add('hero');
  return card;
}

function doneCard(c, nowE) {
  const card = el('div', 'card completed');
  card.appendChild(el('div', 'title', T(c.name)));
  card.appendChild(el('div', 'when',
    `✓ ${EN() ? 'accepted' : '已验收'} · ${agoStr(nowE, c.accepted_at)}`));
  if (c.id === HERO) card.classList.add('hero');
  return card;
}

function debtCard(d) {
  const card = el('div', 'card debt');
  card.appendChild(el('div', 'title', T(d.title)));
  card.appendChild(el('div', 'when dodhead', T(d.summary)));
  const chips = el('div', 'chips');
  chips.appendChild(el('span', `chip ${d.hardness === 'hard' ? 'hard' : ''}`, d.hardness));
  chips.appendChild(el('span', 'chip', d.type));
  card.appendChild(chips);
  const s = (d.sources || [])[0];
  if (s) card.appendChild(el('div', 'quote',
    EN() ? `${s.who} · ${s.channel}: “${T(s.quote)}”`
         : `${s.who} · ${s.channel}：“${s.quote}”`));
  return card;
}

function buildPane(scene) {
  const nowE = isoToEpoch(scene.generated_at);
  const pane = el('div', 'pane');
  const running = [...(scene.needs_input || []), ...(scene.running || [])];
  const cols = [
    [T('提案 · proposals'), scene.needs_approval, (c) => naCard(c), true],
    [T('运行中 · running'), running, (r) => runCard(r, nowE), false],
    [T('待验收 · review'), scene.review, (r) => reviewCard(r, nowE), false],
    [T('储备 · backlog'), scene.debt, (d) => debtCard(d), false],
    [T('已验收 · done'), scene.completed, (c) => doneCard(c, nowE), false],
  ];
  for (const [head, items, render, quickCap] of cols) {
    const col = el('div', 'col');
    const h = el('div', 'colhead');
    h.appendChild(el('span', null, head));
    h.appendChild(el('span', 'count', String((items || []).length)));
    col.appendChild(h);
    const body = el('div', 'colbody');
    if (quickCap) body.appendChild(el('div', 'qcap', T('＋ 一句话，AI 来研究并提案…')));
    (items || []).forEach((it) => body.appendChild(render(it)));
    col.appendChild(body);
    pane.appendChild(col);
  }
  return pane;
}

// ---------------------------------------------------------------- build DOM
function build() {
  const vp = el('div'); vp.id = 'viewport';
  document.body.appendChild(vp);

  // camera + mac window + panes
  const cam = el('div'); cam.id = 'camera'; vp.appendChild(cam);
  const win = el('div'); win.id = 'macwin'; cam.appendChild(win);
  const tb = el('div'); tb.id = 'titlebar';
  const tr = el('div', 'traffic');
  ['r', 'y', 'g'].forEach((k) => tr.appendChild(el('span', k)));
  tb.appendChild(tr);
  const wt = el('div'); wt.id = 'wintitle';
  wt.textContent = T("Zelin's AI Assistant — 任务台");
  tb.appendChild(wt);
  win.appendChild(tb);
  const body = el('div'); body.id = 'winbody'; win.appendChild(body);
  const sb = el('div'); sb.id = 'sidebar';
  sb.appendChild(el('div', 'appname', "Zelin's AI Assistant"));
  [['📋', '任务台', true], ['💬', '问问助手', false], ['🧩', '依赖检查', false],
   ['🎙️', '录制与 ingest', false], ['🗑️', '回收站', false], ['🗄', '归档', false],
   ['⚙️', '设置', false], ['ℹ️', '关于', false]]
    .forEach(([ico, name, act]) => {
      const n = el('div', `nav ${act ? 'active' : ''}`);
      n.appendChild(el('span', null, ico));
      n.appendChild(el('span', null, T(name)));
      sb.appendChild(n);
    });
  body.appendChild(sb);
  const bw = el('div'); bw.id = 'boardwrap'; body.appendChild(bw);
  const bh = el('div'); bh.id = 'boardheader';
  bh.textContent = T('数据生成于 刚刚'); bw.appendChild(bh);
  for (const name of PANE_ORDER) {
    const p = buildPane(window.SCENES[name]);
    p.dataset.scene = name;
    // hero-focus shots: everything but the hero card dims (reference-video
    // style — one idea per shot). The 'done' pane is the wide shot: no dim.
    if (name !== 'done') p.classList.add('focus');
    bw.appendChild(p);
  }

  // cursor + ripple live in window space so they scale with the camera
  const cur = el('div'); cur.id = 'cursor';
  cur.innerHTML = '<svg viewBox="0 0 28 40" width="34" height="46">'
    + '<path d="M3 1 L3 30 L10 24 L14.5 37 L19.5 35 L15 22.5 L25 22.5 Z" '
    + 'fill="#fff" stroke="#111" stroke-width="1.6"/></svg>';
  win.appendChild(cur);
  const rip = el('div'); rip.id = 'ripple'; win.appendChild(rip);

  // ---- full-screen overlays
  const title = el('div', 'overlay'); title.id = 'titlecard';
  const icon = el('img'); icon.src = '../build/icon.png'; icon.alt = ''; title.appendChild(icon);
  title.appendChild(splitWords(el('div', 'bigtitle'), TEXTS.title_big));
  title.appendChild(splitWords(el('div', 'bigsub'), T(TEXTS.title_sub_cn)));
  const tse = el('div', 'bigsub'); tse.style.fontSize = '2.2vh';
  splitWords(tse, TEXTS.title_sub_en); title.appendChild(tse);
  vp.appendChild(title);

  const rec = el('div', 'overlay'); rec.id = 'recscene';
  const badges = el('div'); badges.id = 'recbadges';
  const b1 = el('div', 'recbadge'); b1.appendChild(el('span', 'reddot'));
  b1.appendChild(el('span', null, T('会议录音中'))); badges.appendChild(b1);
  const b2 = el('div', 'recbadge'); b2.appendChild(el('span', null, '🖥️'));
  b2.appendChild(el('span', null, T('录屏中'))); badges.appendChild(b2);
  rec.appendChild(badges);
  const wave = el('div'); wave.id = 'wave';
  for (let i = 0; i < 42; i++) wave.appendChild(el('span'));
  rec.appendChild(wave);
  const qb = el('div'); qb.id = 'quotebubble';
  qb.appendChild(el('div', 'who', T(REC.who)));
  const qt = el('span'); qt.id = 'quotetext'; qb.appendChild(qt);
  const caret = el('span', 'caret'); caret.id = 'quotecaret'; qb.appendChild(caret);
  rec.appendChild(qb);
  const rl = el('div'); rl.id = 'radarline';
  rl.appendChild(el('span', null, T('📡 radar 已捕获')));
  rl.appendChild(el('span', 'arrow', '→'));
  rl.appendChild(el('span', null, T('生成提案')));
  rec.appendChild(rl);
  vp.appendChild(rec);

  const grid = el('div', 'overlay'); grid.id = 'gridscene';
  const gw = el('div'); gw.id = 'gridwrap';
  const g = el('div'); g.id = 'grid';
  for (const [ico, cn, en] of GRID_ITEMS) {
    const tcell = el('div', 'tile');
    tcell.appendChild(el('div', 'ico', ico));
    tcell.appendChild(el('div', 'cn', T(cn)));
    // in EN mode drop sublabels that would just repeat the main label
    if (!(EN() && T(cn).toLowerCase() === T(en).toLowerCase())) {
      tcell.appendChild(el('div', 'en', T(en)));
    }
    g.appendChild(tcell);
  }
  gw.appendChild(g); grid.appendChild(gw);
  const gc = el('div'); gc.id = 'gridcaption';
  gc.appendChild(splitWords(el('div', 'cngc'), T(TEXTS.grid_cn)));
  if (!(EN() && T(TEXTS.grid_cn).toLowerCase() === TEXTS.grid_en.toLowerCase())) {
    gc.appendChild(el('div', 'en', TEXTS.grid_en));
  }
  grid.appendChild(gc);
  vp.appendChild(grid);

  const end = el('div', 'overlay'); end.id = 'endcard';
  const eicon = el('img'); eicon.src = '../build/icon.png'; eicon.alt = ''; end.appendChild(eicon);
  end.appendChild(el('div', 'bigtitle', TEXTS.title_big));
  end.appendChild(el('div', 'url', TEXTS.end_url));
  end.appendChild(el('div', 'lictag', TEXTS.end_tag));
  vp.appendChild(end);

  // caption scrim — text never fights the busy board (reference-video rule:
  // words get their own space)
  const scrim = el('div'); scrim.id = 'capscrim'; vp.appendChild(scrim);

  // lower-third caption cues, prebuilt for determinism.
  // zh build: big zh line + small en line; en build: one big en line.
  const cap = el('div'); cap.id = 'caption'; vp.appendChild(cap);
  for (const cue of CAPTIONS) {
    const c = el('div', 'capcue');
    c.style.position = 'absolute'; c.style.left = '0'; c.style.right = '0';
    c.appendChild(splitWords(el('div', 'cn'), T(cue.cn)));
    if (!EN()) c.appendChild(splitWords(el('div', 'en'), cue.en));
    cap.appendChild(c);
    cue._el = c;
  }

  const veil = el('div'); veil.id = 'fadeveil';
  veil.style.cssText = 'position:absolute;inset:0;background:#000;opacity:0;z-index:99;';
  vp.appendChild(veil);
}

// hero-fly ghosts: a simplified copy of the hero card that physically travels
// to its next column across the approve / accept cuts (reference-video style
// continuity — the card visibly MOVES instead of teleporting between cuts).
const FLIGHTS = [];
function buildGhosts() {
  const win = $('#macwin');
  const mk = (labelZh, fromKey, toKey, t0, dur) => {
    const g = el('div', 'flyghost', T(labelZh));
    win.appendChild(g);
    FLIGHTS.push({ el: g, from: rects[fromKey], to: rects[toKey], t0, dur });
  };
  mk('example-bench: leaderboard 一键导出评测报告',
     'initial|.hero', 'approved|.hero', TL.initial_end, 0.55);
  mk('example-bench: leaderboard 一键导出评测报告',
     'review|.hero', 'done|.hero', TL.review_end + 0.05, 0.6);
}

// --------------------------------------------------------------- measuring
const rects = {};
function measure() {
  const win = $('#macwin');
  const wr = win.getBoundingClientRect();
  rects['window'] = { x: wr.left, y: wr.top, w: wr.width, h: wr.height };
  for (const pane of document.querySelectorAll('.pane')) {
    const name = pane.dataset.scene;
    pane.style.opacity = 1; // ensure layout is realized
    for (const sel of ['.hero', '.hero .btn.approve', '.hero .btn.accept']) {
      const e = pane.querySelector(sel);
      if (!e) continue;
      const r = e.getBoundingClientRect();
      rects[`${name}|${sel}`] = { x: r.left, y: r.top, w: r.width, h: r.height };
    }
    pane.style.opacity = 0;
  }
}
function rectFor(target, pad = 0) {
  const key = target[1] === 'window' ? 'window' : `${target[0]}|${target[1]}`;
  const r = rects[key] || rects['window'];
  return { x: r.x - pad, y: r.y - pad, w: r.w + 2 * pad, h: r.h + 2 * pad };
}
function anchor(target, ax, ay) {
  const r = rectFor(target, 0);
  return { x: r.x + r.w * ax, y: r.y + r.h * ay };
}
function lerpRect(a, b, p) {
  return { x: lerp(a.x, b.x, p), y: lerp(a.y, b.y, p),
           w: lerp(a.w, b.w, p), h: lerp(a.h, b.h, p) };
}

// ------------------------------------------------------------------- seek
function wordsIn(rootEl, t, t0, stagger = 0.045, rise = 18) {
  const ws = rootEl.querySelectorAll(':scope > .w, :scope .w');
  ws.forEach((w, i) => {
    const p = easeOut(seg(t, t0 + i * stagger, t0 + i * stagger + 0.4));
    w.style.opacity = p;
    w.style.transform = `translateY(${(1 - p) * rise}px)`;
  });
}

function seek(t) {
  const vw = window.innerWidth, vh = window.innerHeight;

  // ---- camera
  let rect = rectFor(['done', 'window'], 0);
  for (let i = 0; i < CAM_CUES.length; i++) {
    const cur = CAM_CUES[i], nxt = CAM_CUES[i + 1];
    if (t < cur.t && i === 0) { rect = rectFor(cur.target, cur.pad); break; }
    if (t >= cur.t && (!nxt || t < nxt.t)) {
      rect = rectFor(cur.target, cur.pad);
      if (nxt && !nxt.cut) {
        const p = easeIO(seg(t, cur.t, nxt.t));
        rect = lerpRect(rect, rectFor(nxt.target, nxt.pad), p);
      }
      break;
    }
  }
  // keep close-ups from drifting past the window edges
  const wr = rects['window'];
  if (wr && rect.w < wr.w) {
    rect.x = Math.max(wr.x - 30, Math.min(rect.x, wr.x + wr.w + 30 - rect.w));
  }
  if (wr && rect.h < wr.h) {
    rect.y = Math.max(wr.y - 30, Math.min(rect.y, wr.y + wr.h + 30 - rect.h));
  }

  const s = Math.min(vw / rect.w, vh / rect.h);
  const tx = vw / 2 - s * (rect.x + rect.w / 2);
  const ty = vh / 2 - s * (rect.y + rect.h / 2);
  const cam = $('#camera');
  cam.style.transform = `translate(${tx}px, ${ty}px) scale(${s})`;
  cam.style.opacity = seg(t, TL.rec_end - 0.12, TL.rec_end + 0.45)
    * (1 - seg(t, TL.done_end - 0.3, TL.done_end + 0.05));

  // ---- panes (crossfade or hard cut)
  let active = 0;
  for (let i = 0; i < PANE_CUES.length; i++) if (t >= PANE_CUES[i].t) active = i;
  document.querySelectorAll('.pane').forEach((p) => { p.style.opacity = 0; });
  const cue = PANE_CUES[active];
  const paneEl = (name) => document.querySelector(`.pane[data-scene="${name}"]`);
  const actEl = paneEl(cue.pane);
  if (t >= cue.t && cue.fade > 0 && active > 0 && t < cue.t + cue.fade) {
    const p = seg(t, cue.t, cue.t + cue.fade);
    actEl.style.opacity = p;
    paneEl(PANE_CUES[active - 1].pane).style.opacity = 1 - p;
  } else {
    actEl.style.opacity = 1;
  }

  // ---- hero pulse right after every pane cut
  for (const c of PANE_CUES) {
    const hero = paneEl(c.pane).querySelector('.hero');
    if (!hero) continue;
    const local = t - c.t;
    const on = local >= 0 && local < 1.6;
    hero.classList.toggle('glow', on);
    const pop = on ? 1 + 0.045 * (1 - easeOut(clamp01(local / 0.8))) : 1;
    hero.style.transform = `scale(${pop})`;
    hero.style.opacity = 1;
  }

  // ---- hero-fly ghosts (approve / accept moments)
  for (const f of FLIGHTS) {
    const local = t - f.t0;
    const active = local >= 0 && local < f.dur + 0.18 && f.from && f.to;
    f.el.style.opacity = 0;
    if (!active) continue;
    const p = easeIO(clamp01(local / f.dur));
    f.el.style.left = `${lerp(f.from.x, f.to.x, p)}px`;
    f.el.style.top = `${lerp(f.from.y, f.to.y, p)}px`;
    f.el.style.width = `${lerp(f.from.w, f.to.w, p)}px`;
    f.el.style.height = `${lerp(96, Math.min(f.to.h, 120), p)}px`;
    f.el.style.opacity = 1 - seg(local, f.dur, f.dur + 0.18);
    // the landing card stays hidden until the ghost arrives
    if (p < 0.92) {
      const landPane = f.to === rects['approved|.hero'] ? 'approved' : 'done';
      const landing = paneEl(landPane).querySelector('.hero');
      if (landing) landing.style.opacity = 0;
    }
  }

  // ---- spinners (raising placeholders) keep turning
  document.querySelectorAll('.spinner').forEach((sp) => {
    sp.style.transform = `rotate(${(t * 320) % 360}deg)`;
  });

  // ---- proposal cascade (initial pane hero card children)
  const casc = paneEl('initial').querySelectorAll('.hero .cascade');
  casc.forEach((c, i) => {
    const p = easeOut(seg(t, TL.captured_end + 0.2 + i * 0.11, TL.captured_end + 0.2 + i * 0.11 + 0.45));
    c.style.opacity = p;
    c.style.transform = `translateY(${(1 - p) * 16}px)`;
  });

  // ---- review checklist ticks
  paneEl('review').querySelectorAll('.hero .checkitem').forEach((it, i) => {
    const done = t >= TL.working_end + 0.9 + i * 0.45;
    it.classList.toggle('checked', done);
    it.querySelector('.box').textContent = done ? '☑' : '☐';
  });

  // ---- cursor + clicks
  const cur = $('#cursor'), rip = $('#ripple');
  cur.style.opacity = 0; rip.style.opacity = 0;
  for (const show of CURSOR_CUES.show) {
    if (t < show.t0 || t > show.t1 + 0.05) continue;
    cur.style.opacity = seg(t, show.t0, show.t0 + 0.25);
    let pos = anchor(show.path[0].target, show.path[0].ax, show.path[0].ay);
    for (let i = 0; i < show.path.length - 1; i++) {
      const a = show.path[i], b = show.path[i + 1];
      if (t >= a.t && t <= b.t) {
        const p = easeIO(seg(t, a.t, b.t));
        const pa = anchor(a.target, a.ax, a.ay), pb = anchor(b.target, b.ax, b.ay);
        pos = { x: lerp(pa.x, pb.x, p), y: lerp(pa.y, pb.y, p) };
      } else if (t > b.t) {
        pos = anchor(b.target, b.ax, b.ay);
      }
    }
    let dip = 1;
    for (const cl of CURSOR_CUES.clicks) dip = Math.min(dip, 1 - 0.14 * (1 - clamp01(Math.abs(t - cl.t) / 0.14)));
    cur.style.transform = `translate(${pos.x}px, ${pos.y}px) scale(${dip})`;
  }
  for (const cl of CURSOR_CUES.clicks) {
    const p = seg(t, cl.t, cl.t + 0.5);
    if (p > 0 && p < 1) {
      const c = anchor(cl.target, 0.5, 0.5);
      rip.style.left = `${c.x}px`; rip.style.top = `${c.y}px`;
      rip.style.opacity = 0.9 * (1 - p);
      rip.style.transform = `translate(-50%,-50%) scale(${0.2 + 1.6 * easeOut(p)})`;
    }
    // flash the clicked button
    const btn = document.querySelector(
      `.pane[data-scene="${cl.target[0]}"] ${cl.target[1]}`);
    if (btn) btn.style.filter = (t >= cl.t && t < cl.t + 0.4)
      ? `brightness(${1 + 0.8 * (1 - seg(t, cl.t, cl.t + 0.4))})` : 'none';
  }

  // ---- title card
  const title = $('#titlecard');
  const tIn = seg(t, 0.0, 0.4), tOut = 1 - seg(t, TL.title_end - 0.45, TL.title_end - 0.05);
  title.style.opacity = Math.min(tIn, tOut);
  title.style.transform = `scale(${1 + 0.06 * seg(t, TL.title_end - 0.45, TL.title_end)})`;
  const ticon = title.querySelector('img');
  const ip = easeOutBack(seg(t, 0.25, 0.9));
  ticon.style.opacity = seg(t, 0.25, 0.6);
  ticon.style.transform = `scale(${0.4 + 0.6 * ip})`;
  wordsIn(title.children[1], t, 0.65, 0.045);
  wordsIn(title.children[2], t, 1.45, 0.045);
  wordsIn(title.children[3], t, 2.05, 0.025, 10);

  // ---- recording scene
  const rec = $('#recscene');
  const rIn = seg(t, TL.title_end - 0.15, TL.title_end + 0.35);
  const rOut = 1 - seg(t, TL.rec_end - 0.4, TL.rec_end - 0.05);
  rec.style.opacity = Math.min(rIn, rOut);
  if (rec.style.opacity > 0) {
    const bars = rec.querySelectorAll('#wave span');
    bars.forEach((b, i) => {
      const enter = easeOut(seg(t, TL.title_end + 0.1 + i * 0.02, TL.title_end + 0.45 + i * 0.02));
      const a = Math.abs(Math.sin(i * 0.83 + t * 4.1)) * Math.abs(Math.sin(i * 2.71 - t * 2.3));
      const env = 0.55 + 0.45 * Math.sin(t * 1.7 + i * 0.13);
      b.style.height = `${(8 + 84 * a * env) * enter}%`;
      b.style.opacity = 0.35 + 0.65 * enter;
    });
    const chars = [...T(REC.quote)];
    const n = Math.floor(chars.length * seg(t, REC.type_t0, REC.type_t1));
    $('#quotetext').textContent = chars.slice(0, n).join('');
    $('#quotecaret').style.opacity = (t < REC.type_t1 + 0.8 && (t * 2.4) % 1 < 0.55) ? 1 : 0;
    $('#quotebubble').style.opacity = seg(t, REC.type_t0 - 0.35, REC.type_t0);
    $('#quotebubble').style.transform = `translateY(${(1 - easeOut(seg(t, REC.type_t0 - 0.35, REC.type_t0 + 0.1))) * 24}px)`;
    const rl = $('#radarline');
    const rp = easeOut(seg(t, REC.radar_t, REC.radar_t + 0.5));
    rl.style.opacity = rp;
    rl.style.transform = `translateY(${(1 - rp) * 18}px)`;
    rl.querySelector('.arrow').style.transform = `translateX(${4 * Math.sin(t * 5)}px)`;
  }

  // ---- captions (+ scrim so text never fights the board)
  let capVis = 0;
  for (const cue of CAPTIONS) {
    const on = t >= cue.t0 && t <= cue.t1;
    const out = 1 - seg(t, cue.t1 - 0.25, cue.t1);
    cue._el.style.opacity = on ? out : 0;
    if (on) {
      capVis = Math.max(capVis, out * seg(t, cue.t0, cue.t0 + 0.3));
      wordsIn(cue._el.children[0], t, cue.t0, 0.035);
      if (cue._el.children[1]) wordsIn(cue._el.children[1], t, cue.t0 + 0.3, 0.02, 8);
    }
  }
  // scrim only matters while the board is up — overlays have their own space
  $('#capscrim').style.opacity =
    capVis * (t > TL.rec_end && t < TL.done_end ? 0.9 : 0);

  // ---- feature grid
  const grid = $('#gridscene');
  const gIn = seg(t, TL.done_end - 0.1, TL.done_end + 0.3);
  const gOut = 1 - seg(t, TL.grid_end - 0.4, TL.grid_end - 0.05);
  grid.style.opacity = Math.min(gIn, gOut);
  if (grid.style.opacity > 0) {
    $('#gridwrap').style.transform =
      `scale(${lerp(1.5, 1.0, easeOut(seg(t, TL.done_end, TL.done_end + 1.9)))})`;
    grid.querySelectorAll('.tile').forEach((tile, i) => {
      const p = easeOut(seg(t, TL.done_end + 0.12 + i * 0.06, TL.done_end + 0.5 + i * 0.06));
      tile.style.opacity = p;
      tile.style.transform = `translateY(${(1 - p) * 26}px)`;
    });
    wordsIn($('#gridcaption').children[0], t, TL.done_end + 1.9, 0.035);
    const gcEn = $('#gridcaption').children[1];
    if (gcEn) gcEn.style.opacity = seg(t, TL.done_end + 2.4, TL.done_end + 2.8);
  }

  // ---- end card
  const end = $('#endcard');
  end.style.opacity = seg(t, TL.grid_end - 0.05, TL.grid_end + 0.35);
  const eicon = end.querySelector('img');
  const ep = easeOutBack(seg(t, TL.grid_end + 0.15, TL.grid_end + 0.8));
  eicon.style.transform = `scale(${0.5 + 0.5 * ep})`;
  end.children[1].style.opacity = seg(t, TL.grid_end + 0.5, TL.grid_end + 0.9);
  const url = end.querySelector('.url');
  const up = easeOutBack(seg(t, TL.grid_end + 1.0, TL.grid_end + 1.6));
  url.style.opacity = seg(t, TL.grid_end + 1.0, TL.grid_end + 1.3);
  url.style.transform = `scale(${0.7 + 0.3 * up})`;
  end.querySelector('.lictag').style.opacity = seg(t, TL.grid_end + 1.7, TL.grid_end + 2.1);

  // ---- final fade
  $('#fadeveil').style.opacity = seg(t, TL.fade_out, TL.duration - 0.15);
}

// ------------------------------------------------------------------- init
async function init() {
  window.LANG = new URLSearchParams(location.search).get('lang') === 'en' ? 'en' : 'zh';
  if (window.innerHeight > window.innerWidth) document.body.classList.add('vertical');
  build();
  await document.fonts.ready;
  await new Promise((r) => requestAnimationFrame(() => requestAnimationFrame(r)));
  measure();
  buildGhosts();
  window.seek = seek;
  seek(0);
  window.STAGE_READY = true;

  // manual preview: stage/index.html?play=1
  if (new URLSearchParams(location.search).get('play')) {
    const t0 = performance.now();
    (function loop() {
      seek(((performance.now() - t0) / 1000) % TL.duration);
      requestAnimationFrame(loop);
    })();
  }
}

init();
