// Render stage engine. Builds a faithful DOM replica of the app's kanban from
// demo_seed scene JSON (window.SCENES, generated by prepare.sh) and exposes
// window.seek(t): a PURE function of time — every style it touches is set on
// every call, so frames are deterministic and the capture can scrub anywhere.

/* eslint-disable no-unused-vars */
'use strict';

const $ = (sel) => document.querySelector(sel);
const clamp01 = (v) => Math.max(0, Math.min(1, v));
const lerp = (a, b, p) => a + (b - a) * p;
const seg = (t, a, b) => clamp01((t - a) / Math.max(1e-6, b - a));
const easeIO = (p) => (p < 0.5 ? 4 * p * p * p : 1 - Math.pow(-2 * p + 2, 3) / 2);
const easeOut = (p) => 1 - Math.pow(1 - p, 4);
const easeOutBack = (p) => {
  const c = 2.0;
  return 1 + (c + 1) * Math.pow(p - 1, 3) + c * Math.pow(p - 1, 2);
};

const PANE_ORDER = ['captured', 'initial', 'approved', 'running', 'review', 'done'];
const HERO = 'R-101';
const FRAG_POS = [[10, 34], [36, 28], [64, 33], [12, 62], [57, 60], [33, 76]];

// ------------------------------------------------------------------ helpers
function el(tag, cls, text) {
  const e = document.createElement(tag);
  if (cls) e.className = cls;
  if (text != null) e.textContent = text;
  return e;
}

function splitWords(container, text) {
  // one span per CJK char / latin word, so captions can stagger in
  const parts = text.match(/[A-Za-z0-9$#@._\-—:：]+|\s+|./gu) || [];
  for (const p of parts) {
    const w = el('span', 'w', p);
    container.appendChild(w);
  }
  return container;
}

function isoToEpoch(s) { return Math.floor(Date.parse(s) / 1000); }

const EN = () => window.LANG === 'en';

// time strings mirror the app's real L() pairs in Cards.swift
function agoStr(nowE, e) {
  const m = Math.round((nowE - e) / 60);
  if (m < 1) return EN() ? 'just now' : '刚刚';
  if (m < 60) return EN() ? `${m}m ago` : `${m}分钟前`;
  const h = Math.round(m / 60);
  if (h < 24) return EN() ? `${h}h ago` : `${h}小时前`;
  const d = Math.round(h / 24);
  return EN() ? `${d}d ago` : `${d}天前`;
}

function durStr(sec) {
  if (sec < 60) { const s = Math.max(1, Math.round(sec)); return EN() ? `${s}s` : `${s}秒`; }
  const m = Math.round(sec / 60);
  if (m < 60) return EN() ? `${m}m` : `${m}分钟`;
  const h = Math.round(m / 6) / 10;
  return EN() ? `${h}h` : `${h}小时`;
}

function repoName(p) { return (p || '').split('/').pop(); }

// -------------------------------------------------------------- card DOM
function chipsFor(c) {
  const box = el('div', 'chips cascade');
  box.appendChild(el('span', 'chip tier', T(`${c.tier} · ${c.tier_hint}`)));
  if (c.delivery_mode === 'chat') box.appendChild(el('span', 'chip chat', T('交付：聊天成稿')));
  if (c.deadline) box.appendChild(el('span', 'chip deadline',
    EN() ? `Due ${c.deadline} (${c.days_left}d)` : `截止 ${c.deadline} (${c.days_left}d)`));
  if (c.hardness) box.appendChild(el('span', `chip ${c.hardness === 'hard' ? 'hard' : ''}`, c.hardness));
  if (c.show_cost && c.cost_usd != null) box.appendChild(el('span', 'chip cost', `$${c.cost_usd}`));
  if (c.repeated > 1) box.appendChild(el('span', 'chip',
    EN() ? `Repeated ×${c.repeated}` : `重复 ×${c.repeated}`));
  if (c.green_sign) box.appendChild(el('span', 'chip gsign', T('需 manager green-sign（只出草稿）')));
  return box;
}

function naCard(c) {
  if (c.processing) {
    const card = el('div', 'card processing');
    card.appendChild(el('div', 'spinner'));
    const body = el('div');
    body.appendChild(el('div', 'title', T(c.title)));
    body.appendChild(el('div', 'sub', T('AI 研究中…（补全上下文、生成提案）')));
    card.appendChild(body);
    if (c.id === HERO) card.classList.add('hero');
    return card;
  }
  const card = el('div', 'card');
  card.appendChild(el('div', 'title', T(c.title)));
  const kind = c.target_kind === 'new'
    ? (EN() ? `🟢 New repo: ${c.target_name}` : `🟢 新建 repo: ${c.target_name}`)
    : (EN() ? `🟠 Modify existing: ${c.target_name}` : `🟠 修改现有: ${c.target_name}`);
  const meta = el('div', `metaline cascade ${c.target_kind === 'new' ? 'new' : ''}`);
  meta.textContent = kind;
  if (c.delivery_mode === 'repo') {
    const d = el('span', 'dim', EN()
      ? ' (draft PR only, main branch untouched)' : '（只提 draft PR，不动主分支）');
    meta.appendChild(d);
  }
  card.appendChild(meta);
  card.appendChild(chipsFor(c));
  if (c.dod && c.dod.length) {
    card.appendChild(el('div', 'dodhead cascade', T('怎样算办完：')));
    const list = el('div', 'dodlist');
    c.dod.forEach((d, i) => list.appendChild(el('div', 'li cascade', `${i + 1}. ${T(d)}`)));
    card.appendChild(list);
  }
  if (c.disagreement) card.appendChild(el('div', 'disagree cascade',
    (EN() ? '⚠︎ Disagreement: ' : '⚠ 分歧: ') + T(c.disagreement)));
  const row = el('div', 'btnrow cascade');
  row.appendChild(el('div', 'btn approve', T('✓ 批准')));
  row.appendChild(el('div', 'btn reject', T('✕ 拒绝')));
  row.appendChild(el('div', 'btn', T('💬 修改')));
  row.appendChild(el('div', 'btn ghost', T('展开详情 ▸')));
  card.appendChild(row);
  if (c.id === HERO) card.classList.add('hero');
  return card;
}

function runCard(r, nowE) {
  const card = el('div', 'card');
  const row = el('div', 'namerow');
  const blocked = r.state === 'blocked';
  const queued = r.state === 'queued';
  row.appendChild(el('div', `dot ${blocked ? 'orange' : queued ? 'gray' : 'blue'}`));
  const body = el('div');
  body.appendChild(el('div', 'title', T(r.name)));
  const badges = el('div', 'chips');
  if (blocked) {
    badges.appendChild(el('span', 'badge input', T('需输入')));
    badges.appendChild(el('span', 'badge blocked', 'blocked'));
    badges.appendChild(el('span', 'badge', r.short_id));
  } else if (queued) {
    badges.appendChild(el('span', 'badge queued', T('排队中')));
  } else {
    badges.appendChild(el('span', 'badge working', 'working'));
    badges.appendChild(el('span', 'badge', r.short_id));
    if (r.started_at) badges.appendChild(el('span', 'badge', agoStr(nowE, r.started_at)));
    if (r.cwd) badges.appendChild(el('span', 'badge', repoName(r.cwd)));
  }
  body.appendChild(badges);
  const copyLabel = EN() ? 'Click to copy · double-click runs: ' : '单击复制 · 双击在终端运行：';
  if (blocked) body.appendChild(el('div', 'mono',
    `${EN() ? 'Waiting: ' : '等待: '}${r.waiting_for} · ${copyLabel}${r.copy_cmd}`));
  else if (!queued) {
    body.appendChild(el('div', 'mono', `${copyLabel}${r.copy_cmd}`));
    body.appendChild(el('div', 'mono',
      `${EN() ? 'claude agents list name: ' : 'claude agents 列表名: '}${r.agent_name}`));
  }
  if (r.last_error) body.appendChild(el('div', 'errline',
    `${EN() ? 'Error: ' : '错误: '}${r.last_error}`));
  const btns = el('div', 'btnrow');
  btns.appendChild(el('div', 'btn', T('◉ 停止')));
  if (!queued && !blocked) btns.appendChild(el('div', 'btn ghost', T('展开详情 ▸')));
  body.appendChild(btns);
  row.appendChild(body);
  card.appendChild(row);
  if (r.id === HERO) card.classList.add('hero');
  return card;
}

function reviewCard(r, nowE) {
  const card = el('div', 'card');
  const row = el('div', 'namerow');
  row.appendChild(el('div', 'dot blue'));
  const body = el('div');
  body.appendChild(el('div', 'title', T(r.name)));
  const dl = el('div', 'delivered');
  const bold = el('b', null, T('交付了什么：'));
  dl.appendChild(bold);
  dl.appendChild(document.createTextNode((EN() ? ' ' : '') + T(r.delivered_summary)));
  body.appendChild(dl);
  body.appendChild(el('div', 'dodhead', T('验收清单——逐条对照：')));
  const list = el('div', 'dodlist');
  (r.dod || []).forEach((d) => {
    const it = el('div', 'checkitem');
    it.appendChild(el('span', 'box', '☐'));
    it.appendChild(el('span', null, T(d)));
    list.appendChild(it);
  });
  body.appendChild(list);
  const badges = el('div', 'chips');
  if (r.cwd) badges.appendChild(el('span', 'badge', repoName(r.cwd)));
  badges.appendChild(el('span', 'badge',
    `${EN() ? 'took ' : '耗时 '}${durStr(r.review_at - r.dispatched_at)}`));
  badges.appendChild(el('span', 'badge',
    `${EN() ? 'in review ' : '已等待验收 '}${durStr(nowE - r.review_at)}`));
  body.appendChild(badges);
  body.appendChild(el('div', 'mono',
    `${EN() ? 'Click to copy · double-click runs: ' : '单击复制 · 双击在终端运行：'}${r.copy_cmd}`));
  if (r.final_draft) {
    const fd = el('div', 'finaldraft');
    fd.textContent = T(r.final_draft);
    body.appendChild(fd);
  }
  const btns = el('div', 'btnrow');
  btns.appendChild(el('div', 'btn accept', T('✓ 验收')));
  btns.appendChild(el('div', 'btn', T('↩ 打回')));
  if (r.delivery_mode === 'chat') btns.appendChild(el('div', 'btn copyfinal', T('📋 复制成稿')));
  body.appendChild(btns);
  row.appendChild(body);
  card.appendChild(row);
  if (r.id === HERO) card.classList.add('hero');
  if (r.id === 'R-110') card.classList.add('hero2'); // weekly report — S7b subject
  return card;
}

function doneCard(c, nowE) {
  const card = el('div', 'card completed');
  card.appendChild(el('div', 'title', T(c.name)));
  card.appendChild(el('div', 'when',
    `✓ ${EN() ? 'accepted' : '已验收'} · ${agoStr(nowE, c.accepted_at)}`));
  if (c.id === HERO) card.classList.add('hero');
  return card;
}

function debtCard(d) {
  const card = el('div', 'card debt');
  card.appendChild(el('div', 'title', T(d.title)));
  card.appendChild(el('div', 'when dodhead', T(d.summary)));
  const chips = el('div', 'chips');
  chips.appendChild(el('span', `chip ${d.hardness === 'hard' ? 'hard' : ''}`, d.hardness));
  chips.appendChild(el('span', 'chip', d.type));
  card.appendChild(chips);
  const s = (d.sources || [])[0];
  if (s) card.appendChild(el('div', 'quote',
    EN() ? `${s.who} · ${s.channel}: “${T(s.quote)}”`
         : `${s.who} · ${s.channel}：“${s.quote}”`));
  return card;
}

function buildPane(scene) {
  const nowE = isoToEpoch(scene.generated_at);
  const pane = el('div', 'pane');
  const running = [...(scene.needs_input || []), ...(scene.running || [])];
  const cols = [
    [T('提案 · proposals'), scene.needs_approval, (c) => naCard(c), true],
    [T('运行中 · running'), running, (r) => runCard(r, nowE), false],
    [T('待验收 · review'), scene.review, (r) => reviewCard(r, nowE), false],
    [T('储备 · backlog'), scene.debt, (d) => debtCard(d), false],
    [T('已验收 · done'), scene.completed, (c) => doneCard(c, nowE), false],
  ];
  for (const [head, items, render, quickCap] of cols) {
    const col = el('div', 'col');
    const h = el('div', 'colhead');
    h.appendChild(el('span', null, head));
    h.appendChild(el('span', 'count', String((items || []).length)));
    col.appendChild(h);
    const body = el('div', 'colbody');
    if (quickCap) body.appendChild(el('div', 'qcap', T('＋ 一句话，AI 来研究并提案…')));
    (items || []).forEach((it) => body.appendChild(render(it)));
    col.appendChild(body);
    pane.appendChild(col);
  }
  return pane;
}

// ---------------------------------------------------------------- build DOM
function build() {
  const vp = el('div'); vp.id = 'viewport';
  document.body.appendChild(vp);

  // camera + mac window + panes
  const cam = el('div'); cam.id = 'camera'; vp.appendChild(cam);
  const win = el('div'); win.id = 'macwin'; cam.appendChild(win);
  const tb = el('div'); tb.id = 'titlebar';
  const tr = el('div', 'traffic');
  ['r', 'y', 'g'].forEach((k) => tr.appendChild(el('span', k)));
  tb.appendChild(tr);
  const wt = el('div'); wt.id = 'wintitle';
  wt.textContent = T("Zelin's AI Assistant — 任务台");
  tb.appendChild(wt);
  win.appendChild(tb);
  const body = el('div'); body.id = 'winbody'; win.appendChild(body);
  const sb = el('div'); sb.id = 'sidebar';
  sb.appendChild(el('div', 'appname', "Zelin's AI Assistant"));
  [['📋', '任务台', true], ['💬', '问问助手', false], ['🧩', '依赖检查', false],
   ['🎙️', '录制与 ingest', false], ['🗑️', '回收站', false], ['🗄', '归档', false],
   ['⚙️', '设置', false], ['ℹ️', '关于', false]]
    .forEach(([ico, name, act]) => {
      const n = el('div', `nav ${act ? 'active' : ''}`);
      n.appendChild(el('span', null, ico));
      n.appendChild(el('span', null, T(name)));
      sb.appendChild(n);
    });
  body.appendChild(sb);
  const bw = el('div'); bw.id = 'boardwrap'; body.appendChild(bw);
  const bh = el('div'); bh.id = 'boardheader';
  bh.textContent = T('数据生成于 刚刚'); bw.appendChild(bh);
  for (const name of PANE_ORDER) {
    const p = buildPane(window.SCENES[name]);
    p.dataset.scene = name;
    // hero-focus shots: everything but the hero card dims (reference-video
    // style — one idea per shot). The 'done' pane is the wide shot: no dim.
    if (name !== 'done') p.classList.add('focus');
    bw.appendChild(p);
  }

  // cursor + ripple live in window space so they scale with the camera
  const cur = el('div'); cur.id = 'cursor';
  cur.innerHTML = '<svg viewBox="0 0 28 40" width="34" height="46">'
    + '<path d="M3 1 L3 30 L10 24 L14.5 37 L19.5 35 L15 22.5 L25 22.5 Z" '
    + 'fill="#fff" stroke="#111" stroke-width="1.6"/></svg>';
  win.appendChild(cur);
  const rip = el('div'); rip.id = 'ripple'; win.appendChild(rip);

  // ---- full-screen overlays
  const title = el('div', 'overlay'); title.id = 'titlecard';
  const icon = el('img'); icon.src = '../build/icon.png'; icon.alt = ''; title.appendChild(icon);
  title.appendChild(splitWords(el('div', 'bigtitle'), TEXTS.title_big));
  title.appendChild(splitWords(el('div', 'bigsub'), T(TEXTS.title_sub_cn)));
  const tse = el('div', 'bigsub'); tse.style.fontSize = '2.2vh';
  splitWords(tse, TEXTS.title_sub_en); title.appendChild(tse);
  vp.appendChild(title);

  // ---- S1 extraction: mass fragments -> related ones connect -> one card
  const ext = el('div', 'overlay'); ext.id = 'extractscene';
  const badges = el('div'); badges.id = 'recbadges';
  const b1 = el('div', 'recbadge'); b1.appendChild(el('span', 'reddot'));
  b1.appendChild(el('span', null, T('会议录音中'))); badges.appendChild(b1);
  const b2 = el('div', 'recbadge'); b2.appendChild(el('span', null, '🖥️'));
  b2.appendChild(el('span', null, T('录屏中'))); badges.appendChild(b2);
  ext.appendChild(badges);
  const wave = el('div'); wave.id = 'wave';
  for (let i = 0; i < 42; i++) wave.appendChild(el('span'));
  ext.appendChild(wave);
  const fw = el('div'); fw.id = 'fragwrap';
  EXTRACT.frags.forEach((f, i) => {
    const fr = el('div', `frag ${f.rel ? 'rel' : ''} k-${f.kind}`);
    fr.style.left = `${FRAG_POS[i][0]}%`; fr.style.top = `${FRAG_POS[i][1]}%`;
    fr.appendChild(el('div', 'fwho', T(f.who)));
    const body = el('div', 'ftext');
    if (f.hl) {
      const [pre, post] = T(f.text).split(T(f.hl));
      body.appendChild(document.createTextNode(pre ?? ''));
      body.appendChild(el('span', 'hl', T(f.hl)));
      body.appendChild(document.createTextNode(post ?? ''));
    } else body.textContent = T(f.text);
    fr.appendChild(body);
    fw.appendChild(fr);
  });
  ext.appendChild(fw);
  const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
  svg.id = 'fraglines'; svg.setAttribute('preserveAspectRatio', 'none');
  const line = document.createElementNS('http://www.w3.org/2000/svg', 'path');
  line.id = 'fragline'; svg.appendChild(line);
  ext.appendChild(svg);
  const mini = el('div'); mini.id = 'minicard';
  mini.appendChild(el('div', 'mtitle', T(EXTRACT.card_title)));
  const mchips = el('div', 'chips');
  EXTRACT.chips.forEach((c) => mchips.appendChild(el('span', 'chip', T(c))));
  mini.appendChild(mchips);
  ext.appendChild(mini);
  vp.appendChild(ext);

  // ---- S5 terminal overlay (double-click -> live session)
  const term = el('div', 'overlay'); term.id = 'termscene';
  const tw = el('div'); tw.id = 'termwin';
  const ttb = el('div', 'termbar');
  const ttr = el('div', 'traffic');
  ['r', 'y', 'g'].forEach((k) => ttr.appendChild(el('span', k)));
  ttb.appendChild(ttr);
  ttb.appendChild(el('span', 'termtitle', TERM.title));
  tw.appendChild(ttb);
  const tbody = el('div', 'termbody');
  TERM.lines.forEach(([txt]) => tbody.appendChild(el('div', 'tline', txt)));
  tbody.appendChild(el('span', 'tcursor', '▍'));
  tw.appendChild(tbody);
  term.appendChild(tw);
  vp.appendChild(term);

  // ---- S6 merge-review vignette (主卡/副卡 AI verdict)
  const mg = el('div', 'overlay'); mg.id = 'mergescene';
  const mrow = el('div'); mrow.id = 'mergerow';
  for (const [item, cls] of [[MERGE.primary, 'primary'], [MERGE.secondary, 'secondary']]) {
    const c = el('div', `mcard ${cls}`);
    c.appendChild(el('div', 'mtag', T(item.tag)));
    c.appendChild(el('div', 'mtitle', T(item.title)));
    c.appendChild(el('div', 'msel', '✓'));
    mrow.appendChild(c);
  }
  mg.appendChild(mrow);
  const vd = el('div'); vd.id = 'verdict';
  vd.appendChild(el('div', 'vtitle', T(MERGE.verdict)));
  vd.appendChild(el('div', 'vconf', T(MERGE.confidence)));
  const vbtns = el('div', 'btnrow');
  const vacc = el('div', 'btn accept'); vacc.id = 'vaccept'; vacc.textContent = T(MERGE.accept);
  vbtns.appendChild(vacc);
  vbtns.appendChild(el('div', 'btn', T(MERGE.dismiss)));
  vd.appendChild(vbtns);
  mg.appendChild(vd);
  const vcur = el('div'); vcur.id = 'vcursor';
  vcur.innerHTML = '<svg viewBox="0 0 28 40" width="30" height="42">'
    + '<path d="M3 1 L3 30 L10 24 L14.5 37 L19.5 35 L15 22.5 L25 22.5 Z" '
    + 'fill="#fff" stroke="#111" stroke-width="1.6"/></svg>';
  mg.appendChild(vcur);
  const vrip = el('div'); vrip.id = 'vripple'; mg.appendChild(vrip);
  vp.appendChild(mg);

  // ---- S9 phone loop (Slack self-DM photo -> card; iOS approve)
  const ph = el('div', 'overlay'); ph.id = 'phonescene';
  const frame = el('div'); frame.id = 'phoneframe';
  const scr = el('div'); scr.id = 'phonescreen';
  // slack view
  const slack = el('div', 'pview'); slack.id = 'slackview';
  slack.appendChild(el('div', 'phead', T(PHONE.slack_self)));
  const photo = el('div'); photo.id = 'wbphoto';
  const wb = el('div'); wb.id = 'whiteboard';
  wb.appendChild(el('div', 'wbtitle', 'inkweld demo'));
  const wbrow = el('div', 'wbrow');
  ['repo', 'seed 数据', 'PaaS'].forEach((s, i) => {
    if (i > 0) wbrow.appendChild(el('span', 'wbarrow', '→'));
    wbrow.appendChild(el('span', 'wbbox', T(s)));
  });
  wb.appendChild(wbrow);
  wb.appendChild(el('div', 'wbnote', T('✎ 只读演示账号 / reset 脚本')));
  photo.appendChild(wb);
  photo.appendChild(el('div', 'pcap', T(PHONE.photo_caption)));
  slack.appendChild(photo);
  const pcard = el('div'); pcard.id = 'phonecard';
  const psp = el('div', 'spinner'); psp.style.width = '18px'; psp.style.height = '18px';
  pcard.appendChild(psp);
  const pcbody = el('div');
  pcbody.appendChild(el('div', 'pctitle', T(PHONE.card_title)));
  pcbody.appendChild(el('div', 'pcsub', T(PHONE.processing)));
  pcard.appendChild(pcbody);
  slack.appendChild(pcard);
  scr.appendChild(slack);
  // ios view
  const ios = el('div', 'pview'); ios.id = 'iosview';
  ios.appendChild(el('div', 'phead', T(PHONE.ios_header)));
  ios.appendChild(el('div', 'plane', T(PHONE.ios_lane)));
  const icard = el('div'); icard.id = 'ioscard';
  icard.appendChild(el('div', 'pctitle', T(PHONE.card_title)));
  const ichips = el('div', 'chips');
  ichips.appendChild(el('span', 'chip tier', T('T2 · 需文字确认')));
  ichips.appendChild(el('span', 'chip cost', '$85'));
  icard.appendChild(ichips);
  const ibtns = el('div', 'btnrow');
  const iapp = el('div', 'btn approve'); iapp.id = 'iosapprove';
  iapp.textContent = T(PHONE.approve);
  ibtns.appendChild(iapp);
  ibtns.appendChild(el('div', 'btn reject', T('✕ 拒绝')));
  icard.appendChild(ibtns);
  ios.appendChild(icard);
  ios.appendChild(el('div', 'e2enote', T('端到端加密同步 · E2E encrypted')));
  scr.appendChild(ios);
  frame.appendChild(scr);
  ph.appendChild(frame);
  const thumb = el('div'); thumb.id = 'thumb'; ph.appendChild(thumb);
  vp.appendChild(ph);

  const grid = el('div', 'overlay'); grid.id = 'gridscene';
  const gw = el('div'); gw.id = 'gridwrap';
  const g = el('div'); g.id = 'grid';
  for (const [ico, cn, en] of GRID_ITEMS) {
    const tcell = el('div', 'tile');
    tcell.appendChild(el('div', 'ico', ico));
    tcell.appendChild(el('div', 'cn', T(cn)));
    // in EN mode drop sublabels that would just repeat the main label
    if (!(EN() && T(cn).toLowerCase() === T(en).toLowerCase())) {
      tcell.appendChild(el('div', 'en', T(en)));
    }
    g.appendChild(tcell);
  }
  gw.appendChild(g); grid.appendChild(gw);
  const gc = el('div'); gc.id = 'gridcaption';
  gc.appendChild(splitWords(el('div', 'cngc'), T(TEXTS.grid_cn)));
  if (!(EN() && T(TEXTS.grid_cn).toLowerCase() === TEXTS.grid_en.toLowerCase())) {
    gc.appendChild(el('div', 'en', TEXTS.grid_en));
  }
  grid.appendChild(gc);
  vp.appendChild(grid);

  const end = el('div', 'overlay'); end.id = 'endcard';
  const eicon = el('img'); eicon.src = '../build/icon.png'; eicon.alt = ''; end.appendChild(eicon);
  end.appendChild(el('div', 'bigtitle', TEXTS.title_big));
  end.appendChild(el('div', 'url', TEXTS.end_url));
  end.appendChild(el('div', 'lictag', TEXTS.end_tag));
  vp.appendChild(end);

  // caption scrim — text never fights the busy board (reference-video rule:
  // words get their own space)
  const scrim = el('div'); scrim.id = 'capscrim'; vp.appendChild(scrim);

  // lower-third caption cues, prebuilt for determinism.
  // zh build: big zh line + small en line; en build: one big en line.
  const cap = el('div'); cap.id = 'caption'; vp.appendChild(cap);
  for (const cue of CAPTIONS) {
    const c = el('div', 'capcue');
    c.style.position = 'absolute'; c.style.left = '0'; c.style.right = '0';
    c.appendChild(splitWords(el('div', 'cn'), T(cue.cn)));
    if (!EN()) c.appendChild(splitWords(el('div', 'en'), cue.en));
    cap.appendChild(c);
    cue._el = c;
  }

  const veil = el('div'); veil.id = 'fadeveil';
  veil.style.cssText = 'position:absolute;inset:0;background:#000;opacity:0;z-index:99;';
  vp.appendChild(veil);
}

// hero-fly ghosts: a simplified copy of the hero card that physically travels
// to its next column across the approve / accept cuts (reference-video style
// continuity — the card visibly MOVES instead of teleporting between cuts).
const FLIGHTS = [];
function buildGhosts() {
  const win = $('#macwin');
  const mk = (labelZh, fromKey, toKey, t0, dur) => {
    const g = el('div', 'flyghost', T(labelZh));
    win.appendChild(g);
    FLIGHTS.push({ el: g, from: rects[fromKey], to: rects[toKey], t0, dur });
  };
  mk('example-bench: leaderboard 一键导出评测报告',
     'initial|.hero', 'approved|.hero', TL.initial_end, 0.55);
  mk('example-bench: leaderboard 一键导出评测报告',
     'review|.hero', 'done|.hero', TL.review_end + 0.05, 0.6);
}

// --------------------------------------------------------------- measuring
const rects = {};
const vrects = {}; // viewport-space rects for overlay cursors
function measure() {
  const win = $('#macwin');
  const wr = win.getBoundingClientRect();
  rects['window'] = { x: wr.left, y: wr.top, w: wr.width, h: wr.height };
  for (const pane of document.querySelectorAll('.pane')) {
    const name = pane.dataset.scene;
    pane.style.opacity = 1; // ensure layout is realized
    // hero2's final draft is measured EXPANDED so the camera pre-frames it
    const fd = pane.querySelector('.hero2 .finaldraft');
    if (fd) fd.style.maxHeight = '340px';
    for (const sel of ['.hero', '.hero .btn.approve', '.hero .btn.accept',
                       '.hero .mono', '.qcap',
                       '.hero2', '.hero2 .finaldraft', '.hero2 .btn.copyfinal']) {
      const e = pane.querySelector(sel);
      if (!e) continue;
      const r = e.getBoundingClientRect();
      rects[`${name}|${sel}`] = { x: r.left, y: r.top, w: r.width, h: r.height };
    }
    if (fd) fd.style.maxHeight = '';
    pane.style.opacity = 0;
  }
  // overlay hotspots (viewport space; opacity doesn't affect geometry)
  for (const [key, sel] of [['vaccept', '#vaccept'], ['iosapprove', '#iosapprove']]) {
    const r = $(sel).getBoundingClientRect();
    vrects[key] = { x: r.left, y: r.top, w: r.width, h: r.height };
  }
}

// ephemeral quick-capture card: absolutely anchored right under the initial
// pane's composer; pops during S3, stays out of every pane's layout flow
let qcCard = null;
function buildQcCard() {
  const pane = document.querySelector('.pane[data-scene="initial"]');
  const body = pane.querySelector('.colbody');
  body.style.position = 'relative';
  const q = pane.querySelector('.qcap');
  qcCard = el('div', 'card processing qccard');
  qcCard.appendChild(el('div', 'spinner'));
  const b = el('div');
  b.appendChild(el('div', 'title', T(QC.text)));
  b.appendChild(el('div', 'sub', T('AI 研究中…（补全上下文、生成提案）')));
  qcCard.appendChild(b);
  qcCard.style.position = 'absolute';
  qcCard.style.left = '0'; qcCard.style.right = '0';
  qcCard.style.top = `${q.offsetTop + q.offsetHeight + 14}px`;
  qcCard.style.zIndex = '5';
  body.appendChild(qcCard);
}
function rectFor(target, pad = 0) {
  const key = target[1] === 'window' ? 'window' : `${target[0]}|${target[1]}`;
  const r = rects[key] || rects['window'];
  return { x: r.x - pad, y: r.y - pad, w: r.w + 2 * pad, h: r.h + 2 * pad };
}
function anchor(target, ax, ay) {
  const r = rectFor(target, 0);
  return { x: r.x + r.w * ax, y: r.y + r.h * ay };
}
function lerpRect(a, b, p) {
  return { x: lerp(a.x, b.x, p), y: lerp(a.y, b.y, p),
           w: lerp(a.w, b.w, p), h: lerp(a.h, b.h, p) };
}

// ------------------------------------------------------------------- seek
function wordsIn(rootEl, t, t0, stagger = 0.045, rise = 18) {
  const ws = rootEl.querySelectorAll(':scope > .w, :scope .w');
  ws.forEach((w, i) => {
    const p = easeOut(seg(t, t0 + i * stagger, t0 + i * stagger + 0.4));
    w.style.opacity = p;
    w.style.transform = `translateY(${(1 - p) * rise}px)`;
  });
}

function cueRect(cue) {
  const r = rectFor(cue.target, cue.pad);
  if (cue.dy) r.y += cue.dy;
  return r;
}

function seek(t) {
  const vw = window.innerWidth, vh = window.innerHeight;

  // ---- camera
  let rect = rectFor(['done', 'window'], 0);
  for (let i = 0; i < CAM_CUES.length; i++) {
    const cur = CAM_CUES[i], nxt = CAM_CUES[i + 1];
    if (t < cur.t && i === 0) { rect = cueRect(cur); break; }
    if (t >= cur.t && (!nxt || t < nxt.t)) {
      rect = cueRect(cur);
      if (nxt && !nxt.cut) {
        const p = easeIO(seg(t, cur.t, nxt.t));
        rect = lerpRect(rect, cueRect(nxt), p);
      }
      break;
    }
  }
  // keep close-ups from drifting past the window edges
  const wr = rects['window'];
  if (wr && rect.w < wr.w) {
    rect.x = Math.max(wr.x - 30, Math.min(rect.x, wr.x + wr.w + 30 - rect.w));
  }
  if (wr && rect.h < wr.h) {
    rect.y = Math.max(wr.y - 30, Math.min(rect.y, wr.y + wr.h + 30 - rect.h));
  }

  const s = Math.min(vw / rect.w, vh / rect.h);
  const tx = vw / 2 - s * (rect.x + rect.w / 2);
  const ty = vh / 2 - s * (rect.y + rect.h / 2);
  const cam = $('#camera');
  cam.style.transform = `translate(${tx}px, ${ty}px) scale(${s})`;
  cam.style.opacity = seg(t, TL.board_in, TL.board_in + 0.55)
    * (1 - seg(t, TL.done_end - 0.3, TL.done_end + 0.05));

  // ---- panes (crossfade or hard cut)
  let active = 0;
  for (let i = 0; i < PANE_CUES.length; i++) if (t >= PANE_CUES[i].t) active = i;
  document.querySelectorAll('.pane').forEach((p) => { p.style.opacity = 0; });
  const cue = PANE_CUES[active];
  const paneEl = (name) => document.querySelector(`.pane[data-scene="${name}"]`);
  const actEl = paneEl(cue.pane);
  if (t >= cue.t && cue.fade > 0 && active > 0 && t < cue.t + cue.fade) {
    const p = seg(t, cue.t, cue.t + cue.fade);
    actEl.style.opacity = p;
    paneEl(PANE_CUES[active - 1].pane).style.opacity = 1 - p;
  } else {
    actEl.style.opacity = 1;
  }

  // ---- hero pulse right after every pane cut
  for (const c of PANE_CUES) {
    const hero = paneEl(c.pane).querySelector('.hero');
    if (!hero) continue;
    const local = t - c.t;
    const on = local >= 0 && local < 1.6;
    hero.classList.toggle('glow', on);
    const pop = on ? 1 + 0.045 * (1 - easeOut(clamp01(local / 0.8))) : 1;
    hero.style.transform = `scale(${pop})`;
    hero.style.opacity = 1;
  }

  // ---- hero-fly ghosts (approve / accept moments)
  for (const f of FLIGHTS) {
    const local = t - f.t0;
    const active = local >= 0 && local < f.dur + 0.18 && f.from && f.to;
    f.el.style.opacity = 0;
    if (!active) continue;
    const p = easeIO(clamp01(local / f.dur));
    f.el.style.left = `${lerp(f.from.x, f.to.x, p)}px`;
    f.el.style.top = `${lerp(f.from.y, f.to.y, p)}px`;
    f.el.style.width = `${lerp(f.from.w, f.to.w, p)}px`;
    f.el.style.height = `${lerp(96, Math.min(f.to.h, 120), p)}px`;
    f.el.style.opacity = 1 - seg(local, f.dur, f.dur + 0.18);
    // the landing card stays hidden until the ghost arrives
    if (p < 0.92) {
      const landPane = f.to === rects['approved|.hero'] ? 'approved' : 'done';
      const landing = paneEl(landPane).querySelector('.hero');
      if (landing) landing.style.opacity = 0;
    }
  }

  // ---- spinners (raising placeholders) keep turning
  document.querySelectorAll('.spinner').forEach((sp) => {
    sp.style.transform = `rotate(${(t * 320) % 360}deg)`;
  });

  // ---- proposal cascade (initial pane hero card children)
  const casc = paneEl('initial').querySelectorAll('.hero .cascade');
  casc.forEach((c, i) => {
    const p = easeOut(seg(t, TL.captured_end + 0.2 + i * 0.11, TL.captured_end + 0.2 + i * 0.11 + 0.45));
    c.style.opacity = p;
    c.style.transform = `translateY(${(1 - p) * 16}px)`;
  });

  // ---- review checklist ticks
  paneEl('review').querySelectorAll('.hero .checkitem').forEach((it, i) => {
    const done = t >= TL.working_end + 0.9 + i * 0.45;
    it.classList.toggle('checked', done);
    it.querySelector('.box').textContent = done ? '☑' : '☐';
  });

  // ---- cursor + clicks
  const cur = $('#cursor'), rip = $('#ripple');
  cur.style.opacity = 0; rip.style.opacity = 0;
  for (const show of CURSOR_CUES.show) {
    if (t < show.t0 || t > show.t1 + 0.05) continue;
    cur.style.opacity = seg(t, show.t0, show.t0 + 0.25);
    let pos = anchor(show.path[0].target, show.path[0].ax, show.path[0].ay);
    for (let i = 0; i < show.path.length - 1; i++) {
      const a = show.path[i], b = show.path[i + 1];
      if (t >= a.t && t <= b.t) {
        const p = easeIO(seg(t, a.t, b.t));
        const pa = anchor(a.target, a.ax, a.ay), pb = anchor(b.target, b.ax, b.ay);
        pos = { x: lerp(pa.x, pb.x, p), y: lerp(pa.y, pb.y, p) };
      } else if (t > b.t) {
        pos = anchor(b.target, b.ax, b.ay);
      }
    }
    let dip = 1;
    for (const cl of CURSOR_CUES.clicks) dip = Math.min(dip, 1 - 0.14 * (1 - clamp01(Math.abs(t - cl.t) / 0.14)));
    cur.style.transform = `translate(${pos.x}px, ${pos.y}px) scale(${dip})`;
  }
  for (const cl of CURSOR_CUES.clicks) {
    const p = seg(t, cl.t, cl.t + 0.5);
    if (p > 0 && p < 1) {
      const c = anchor(cl.target, 0.5, 0.5);
      rip.style.left = `${c.x}px`; rip.style.top = `${c.y}px`;
      rip.style.opacity = 0.9 * (1 - p);
      rip.style.transform = `translate(-50%,-50%) scale(${0.2 + 1.6 * easeOut(p)})`;
    }
    // flash the clicked button
    const btn = document.querySelector(
      `.pane[data-scene="${cl.target[0]}"] ${cl.target[1]}`);
    if (btn) btn.style.filter = (t >= cl.t && t < cl.t + 0.4)
      ? `brightness(${1 + 0.8 * (1 - seg(t, cl.t, cl.t + 0.4))})` : 'none';
  }

  // ---- title card
  const title = $('#titlecard');
  const tIn = seg(t, 0.0, 0.35), tOut = 1 - seg(t, TL.title_end - 0.4, TL.title_end - 0.05);
  title.style.opacity = Math.min(tIn, tOut);
  title.style.transform = `scale(${1 + 0.06 * seg(t, TL.title_end - 0.4, TL.title_end)})`;
  const ticon = title.querySelector('img');
  const ip = easeOutBack(seg(t, 0.15, 0.7));
  ticon.style.opacity = seg(t, 0.15, 0.45);
  ticon.style.transform = `scale(${0.4 + 0.6 * ip})`;
  wordsIn(title.children[1], t, 0.45, 0.04);
  wordsIn(title.children[2], t, 1.0, 0.04);
  wordsIn(title.children[3], t, 1.45, 0.02, 10);

  // ---- S1 extraction scene
  const ext = $('#extractscene');
  const tt = TL.title_end;
  const eIn = seg(t, tt - 0.15, tt + 0.3);
  const eOut = 1 - seg(t, TL.extract_end - 0.6, TL.extract_end - 0.1);
  ext.style.opacity = Math.min(eIn, eOut);
  if (ext.style.opacity > 0) {
    ext.querySelectorAll('#wave span').forEach((b, i) => {
      const enter = easeOut(seg(t, tt + 0.05 + i * 0.015, tt + 0.35 + i * 0.015));
      const a = Math.abs(Math.sin(i * 0.83 + t * 4.1)) * Math.abs(Math.sin(i * 2.71 - t * 2.3));
      const env = 0.55 + 0.45 * Math.sin(t * 1.7 + i * 0.13);
      b.style.height = `${(6 + 70 * a * env) * enter}%`;
      b.style.opacity = 0.35 + 0.65 * enter;
    });
    // fragments rain in, unrelated ones recede, related ones light + connect
    const frags = ext.querySelectorAll('.frag');
    const dimT = tt + 2.8, convT = tt + 4.4;
    frags.forEach((fr, i) => {
      const enter = easeOut(seg(t, tt + 1.0 + i * 0.22, tt + 1.5 + i * 0.22));
      const rel = fr.classList.contains('rel');
      const dim = rel ? 1 : 1 - 0.75 * seg(t, dimT, dimT + 0.6);
      const conv = rel ? easeIO(seg(t, convT, convT + 0.8)) : 0;
      const gone = rel ? 0 : seg(t, convT, convT + 0.5);
      // converge toward the minicard spot (50%, 58%)
      const dx = (50 - parseFloat(fr.style.left) - 11) * conv;
      const dy2 = (58 - parseFloat(fr.style.top) - 5) * conv;
      fr.style.opacity = enter * dim * (1 - gone) * (1 - 0.999 * seg(t, convT + 0.55, convT + 0.8));
      fr.style.transform = `translate(${dx}vw, ${dy2}vh) `
        + `translateY(${(1 - enter) * 24}px) scale(${1 - 0.75 * conv})`;
      fr.classList.toggle('lit', rel && t > dimT + 0.25);
    });
    // connecting line between the two related fragments
    const lineP = seg(t, tt + 3.3, tt + 4.0);
    const line = $('#fragline');
    if (lineP > 0 && t < convT + 0.5) {
      const W = vw, H = vh;
      const a = { x: (FRAG_POS[1][0] + 11) / 100 * W, y: (FRAG_POS[1][1] + 7) / 100 * H };
      const b = { x: (FRAG_POS[4][0] + 11) / 100 * W, y: (FRAG_POS[4][1] + 5) / 100 * H };
      $('#fraglines').setAttribute('viewBox', `0 0 ${W} ${H}`);
      line.setAttribute('d', `M ${a.x} ${a.y} Q ${(a.x + b.x) / 2} ${(a.y + b.y) / 2 - 60} ${b.x} ${b.y}`);
      const len = 900;
      line.style.strokeDasharray = len;
      line.style.strokeDashoffset = len * (1 - lineP);
      line.style.opacity = 1 - seg(t, convT, convT + 0.4);
    } else line.style.opacity = 0;
    // the one card they become
    const mini = $('#minicard');
    const mp = easeOutBack(seg(t, convT + 0.3, convT + 0.9));
    mini.style.opacity = seg(t, convT + 0.3, convT + 0.6);
    mini.style.transform = `translate(-50%, -50%) scale(${0.5 + 0.5 * mp})`;
    mini.querySelectorAll('.chip').forEach((c, i) => {
      const cp = easeOutBack(seg(t, convT + 0.7 + i * 0.2, convT + 1.05 + i * 0.2));
      c.style.opacity = seg(t, convT + 0.7 + i * 0.2, convT + 0.9 + i * 0.2);
      c.style.transform = `scale(${0.5 + 0.5 * cp})`;
    });
  }

  // ---- S3 quick-capture typing in the composer
  const qcap = paneEl('initial').querySelector('.qcap');
  if (t >= TL.qc_start + 0.25 && t <= TL.qc_end + 0.55) {
    const chars = [...T(QC.text)];
    const n = Math.floor(chars.length * seg(t, QC.type_t0, QC.type_t1));
    const caret = (t < QC.enter_t + 0.4 && (t * 2.6) % 1 < 0.55) ? '▍' : '';
    qcap.textContent = '＋ ' + chars.slice(0, n).join('') + caret;
    qcap.style.opacity = 1;
    const flash = 1 - clamp01(Math.abs(t - QC.enter_t) / 0.2);
    qcap.style.borderColor = `rgba(177, 140, 255, ${0.25 + 0.7 * flash})`;
    qcap.style.color = '#e8e8ec';
  } else {
    qcap.textContent = T('＋ 一句话，AI 来研究并提案…');
    qcap.style.opacity = ''; qcap.style.borderColor = ''; qcap.style.color = '';
  }
  if (qcCard) {
    const qp = easeOutBack(seg(t, QC.enter_t, QC.enter_t + 0.5));
    // fades back out as the camera returns to the hero card (it sits on top
    // of the flow, so it must not linger over R-101 in the approve shot)
    qcCard.style.opacity = seg(t, QC.enter_t, QC.enter_t + 0.25)
      * (1 - seg(t, TL.qc_end + 0.15, TL.qc_end + 0.55));
    qcCard.style.transform = `translateY(${(1 - qp) * 22}px) scale(${0.92 + 0.08 * qp})`;
    qcCard.classList.toggle('glow', t >= QC.enter_t && t < QC.enter_t + 1.3);
  }

  // ---- S2 chip pulses on the hero proposal (cost / due / tier)
  paneEl('initial').querySelectorAll('.hero .chips .chip').forEach((c, i) => {
    if (i > 3) return;
    const p0 = TL.captured_end + 1.7 + i * 0.4;
    const pp = Math.sin(Math.PI * seg(t, p0, p0 + 0.4));
    c.style.transform = `scale(${1 + 0.14 * pp})`;
    c.style.filter = pp > 0.01 ? `brightness(${1 + 0.5 * pp})` : 'none';
  });

  // ---- S5 terminal overlay
  const term = $('#termscene');
  const tmIn = seg(t, TL.term_in - 0.05, TL.term_in + 0.3);
  const tmOut = 1 - seg(t, TL.term_end - 0.35, TL.term_end - 0.05);
  term.style.opacity = Math.min(tmIn, tmOut);
  if (term.style.opacity > 0) {
    const rise = easeOut(seg(t, TL.term_in, TL.term_in + 0.45));
    $('#termwin').style.transform = `translateY(${(1 - rise) * 46}px) scale(${0.96 + 0.04 * rise})`;
    const lines = term.querySelectorAll('.tline');
    lines.forEach((ln, i) => {
      const off = TL.term_in + 0.15 + TERM.lines[i][1];
      if (i === 0) {
        const chars = TERM.lines[0][0];
        const n = Math.floor(chars.length * seg(t, off, off + 0.4));
        ln.textContent = chars.slice(0, n);
        ln.style.opacity = 1;
      } else {
        ln.style.opacity = seg(t, off, off + 0.2);
        ln.style.transform = `translateX(${(1 - easeOut(seg(t, off, off + 0.3))) * 10}px)`;
      }
    });
    term.querySelector('.tcursor').style.opacity = (t * 2.4) % 1 < 0.55 ? 1 : 0;
  }

  // ---- S6 merge-review vignette
  const mg = $('#mergescene');
  const mgIn = seg(t, TL.term_end - 0.1, TL.term_end + 0.3);
  const mgOut = 1 - seg(t, TL.merge_end - 0.4, TL.merge_end - 0.05);
  mg.style.opacity = Math.min(mgIn, mgOut);
  if (mg.style.opacity > 0) {
    const cards = mg.querySelectorAll('.mcard');
    cards.forEach((c, i) => {
      const enter = easeOut(seg(t, TL.term_end + 0.1 + i * 0.15, TL.term_end + 0.5 + i * 0.15));
      let extra = '';
      if (c.classList.contains('secondary')) {
        const fuse = easeIO(seg(t, MERGE.accept_t + 0.25, MERGE.accept_t + 0.85));
        const pv = vrects['mprimary'], sv = vrects['msecondary'];
        if (pv && sv) extra = ` translate(${(pv.x - sv.x) * fuse}px, ${(pv.y - sv.y) * fuse}px) scale(${1 - 0.8 * fuse})`;
        c.style.opacity = enter * (1 - seg(t, MERGE.accept_t + 0.75, MERGE.accept_t + 0.95));
      } else {
        const pulse = 1 + 0.05 * Math.sin(Math.PI * seg(t, MERGE.accept_t + 0.8, MERGE.accept_t + 1.2));
        extra = ` scale(${pulse})`;
        c.style.opacity = enter;
      }
      c.style.transform = `translateY(${(1 - enter) * 26}px)` + extra;
      const sel = c.querySelector('.msel');
      const sp = easeOutBack(seg(t, MERGE.select_t + i * 0.35, MERGE.select_t + 0.35 + i * 0.35));
      sel.style.opacity = seg(t, MERGE.select_t + i * 0.35, MERGE.select_t + 0.2 + i * 0.35);
      sel.style.transform = `scale(${0.4 + 0.6 * sp})`;
    });
    const vd = $('#verdict');
    const vp2 = easeOut(seg(t, MERGE.verdict_t, MERGE.verdict_t + 0.45));
    vd.style.opacity = vp2 * (1 - seg(t, MERGE.accept_t + 0.5, MERGE.accept_t + 0.8));
    vd.style.transform = `translateY(${(1 - vp2) * 30}px)`;
    // vignette cursor + click
    const vc = $('#vcursor'), vr = $('#vripple'), va = vrects['vaccept'];
    vc.style.opacity = 0; vr.style.opacity = 0;
    if (va && t >= MERGE.verdict_t + 0.4 && t <= MERGE.accept_t + 0.35) {
      vc.style.opacity = seg(t, MERGE.verdict_t + 0.4, MERGE.verdict_t + 0.6);
      const p = easeIO(seg(t, MERGE.verdict_t + 0.5, MERGE.accept_t - 0.08));
      const x = lerp(va.x + va.w / 2 + 210, va.x + va.w / 2, p);
      const y = lerp(va.y + va.h / 2 + 150, va.y + va.h / 2, p);
      const dip = 1 - 0.14 * (1 - clamp01(Math.abs(t - MERGE.accept_t) / 0.14));
      vc.style.transform = `translate(${x}px, ${y}px) scale(${dip})`;
    }
    if (va) {
      const rp = seg(t, MERGE.accept_t, MERGE.accept_t + 0.45);
      if (rp > 0 && rp < 1) {
        vr.style.left = `${va.x + va.w / 2}px`; vr.style.top = `${va.y + va.h / 2}px`;
        vr.style.opacity = 0.9 * (1 - rp);
        vr.style.transform = `translate(-50%,-50%) scale(${0.2 + 1.5 * easeOut(rp)})`;
      }
      $('#vaccept').style.filter = (t >= MERGE.accept_t && t < MERGE.accept_t + 0.4)
        ? `brightness(${1 + 0.8 * (1 - seg(t, MERGE.accept_t, MERGE.accept_t + 0.4))})` : 'none';
    }
  }

  // ---- S7b final draft expands + 复制成稿 click
  // spotlight moves from the PR card (hero) to the weekly report (hero2)
  paneEl('review').classList.toggle('late', t >= TL.review_pan + 0.3);
  const fdEl = paneEl('review').querySelector('.hero2 .finaldraft');
  if (fdEl) {
    const open = easeIO(seg(t, TL.review_pan + 0.5, TL.review_pan + 1.3));
    fdEl.style.maxHeight = `${340 * open}px`;
    fdEl.style.opacity = 0.4 + 0.6 * open;
  }
  const cfBtn = paneEl('review').querySelector('.hero2 .btn.copyfinal');
  if (cfBtn) {
    const copied = t >= TL.copy_click + 0.1;
    cfBtn.textContent = copied ? T('已复制 ✓') : T('📋 复制成稿');
    cfBtn.classList.toggle('copied', copied);
  }

  // ---- S9 phone loop
  const ph = $('#phonescene');
  const phIn = seg(t, TL.done_end - 0.05, TL.done_end + 0.35);
  const phOut = 1 - seg(t, TL.phone_end - 0.4, TL.phone_end - 0.05);
  ph.style.opacity = Math.min(phIn, phOut);
  if (ph.style.opacity > 0) {
    const rise = easeOut(seg(t, TL.done_end, TL.done_end + 0.55));
    $('#phoneframe').style.transform = `translateY(${(1 - rise) * 50}px)`;
    const sw = seg(t, TL.phone_switch - 0.15, TL.phone_switch + 0.15);
    $('#slackview').style.opacity = 1 - sw;
    $('#iosview').style.opacity = sw;
    const pp = easeOutBack(seg(t, PHONE.photo_t, PHONE.photo_t + 0.5));
    $('#wbphoto').style.opacity = seg(t, PHONE.photo_t, PHONE.photo_t + 0.25);
    $('#wbphoto').style.transform = `translateY(${(1 - pp) * 46}px)`;
    const cp = easeOutBack(seg(t, PHONE.card_t, PHONE.card_t + 0.5));
    $('#phonecard').style.opacity = seg(t, PHONE.card_t, PHONE.card_t + 0.25);
    $('#phonecard').style.transform = `translateY(${(1 - cp) * 30}px)`;
    // thumb tap on 批准
    const th = $('#thumb'), ia = vrects['iosapprove'];
    th.style.opacity = 0;
    if (ia && t >= PHONE.tap_t - 0.55 && t <= PHONE.tap_t + 0.5) {
      th.style.opacity = 0.55 * seg(t, PHONE.tap_t - 0.55, PHONE.tap_t - 0.3)
        * (1 - seg(t, PHONE.tap_t + 0.25, PHONE.tap_t + 0.5));
      const ap = easeIO(seg(t, PHONE.tap_t - 0.55, PHONE.tap_t - 0.05));
      const x = lerp(ia.x + ia.w / 2 + 60, ia.x + ia.w / 2, ap);
      const y = lerp(ia.y + ia.h / 2 + 90, ia.y + ia.h / 2, ap);
      const dip = 1 - 0.25 * (1 - clamp01(Math.abs(t - PHONE.tap_t) / 0.15));
      th.style.transform = `translate(-50%,-50%) translate(${x}px, ${y}px) scale(${dip})`;
    }
    const iBtn = $('#iosapprove');
    const done = t >= PHONE.tap_t + 0.12;
    iBtn.textContent = done ? T(PHONE.approved) : T(PHONE.approve);
    iBtn.classList.toggle('done', done);
    const slide = easeIO(seg(t, PHONE.tap_t + 0.4, PHONE.tap_t + 0.95));
    $('#ioscard').style.transform = `translateX(${slide * 120}px)`;
    $('#ioscard').style.opacity = 1 - 0.7 * slide;
  }

  // ---- captions (+ scrim so text never fights the board)
  let capVis = 0;
  for (const cue of CAPTIONS) {
    const on = t >= cue.t0 && t <= cue.t1;
    const out = 1 - seg(t, cue.t1 - 0.25, cue.t1);
    cue._el.style.opacity = on ? out : 0;
    if (on) {
      capVis = Math.max(capVis, out * seg(t, cue.t0, cue.t0 + 0.3));
      wordsIn(cue._el.children[0], t, cue.t0, 0.035);
      if (cue._el.children[1]) wordsIn(cue._el.children[1], t, cue.t0 + 0.3, 0.02, 8);
    }
  }
  // scrim only matters while the board is up — overlays have their own space
  $('#capscrim').style.opacity =
    capVis * (t > TL.board_in && t < TL.done_end ? 0.9 : 0);

  // ---- feature grid
  const grid = $('#gridscene');
  const gIn = seg(t, TL.phone_end - 0.1, TL.phone_end + 0.3);
  const gOut = 1 - seg(t, TL.grid_end - 0.4, TL.grid_end - 0.05);
  grid.style.opacity = Math.min(gIn, gOut);
  if (grid.style.opacity > 0) {
    $('#gridwrap').style.transform =
      `scale(${lerp(1.5, 1.0, easeOut(seg(t, TL.phone_end, TL.phone_end + 1.9)))})`;
    grid.querySelectorAll('.tile').forEach((tile, i) => {
      const p = easeOut(seg(t, TL.phone_end + 0.12 + i * 0.06, TL.phone_end + 0.5 + i * 0.06));
      tile.style.opacity = p;
      tile.style.transform = `translateY(${(1 - p) * 26}px)`;
    });
    wordsIn($('#gridcaption').children[0], t, TL.phone_end + 1.6, 0.035);
    const gcEn = $('#gridcaption').children[1];
    if (gcEn) gcEn.style.opacity = seg(t, TL.phone_end + 2.1, TL.phone_end + 2.5);
  }

  // ---- end card
  const end = $('#endcard');
  end.style.opacity = seg(t, TL.grid_end - 0.05, TL.grid_end + 0.35);
  const eicon = end.querySelector('img');
  const ep = easeOutBack(seg(t, TL.grid_end + 0.15, TL.grid_end + 0.8));
  eicon.style.transform = `scale(${0.5 + 0.5 * ep})`;
  end.children[1].style.opacity = seg(t, TL.grid_end + 0.5, TL.grid_end + 0.9);
  const url = end.querySelector('.url');
  const up = easeOutBack(seg(t, TL.grid_end + 1.0, TL.grid_end + 1.6));
  url.style.opacity = seg(t, TL.grid_end + 1.0, TL.grid_end + 1.3);
  url.style.transform = `scale(${0.7 + 0.3 * up})`;
  end.querySelector('.lictag').style.opacity = seg(t, TL.grid_end + 1.7, TL.grid_end + 2.1);

  // ---- final fade
  $('#fadeveil').style.opacity = seg(t, TL.fade_out, TL.duration - 0.15);
}

// ------------------------------------------------------------------- init
async function init() {
  window.LANG = new URLSearchParams(location.search).get('lang') === 'en' ? 'en' : 'zh';
  if (window.innerHeight > window.innerWidth) document.body.classList.add('vertical');
  build();
  await document.fonts.ready;
  await new Promise((r) => requestAnimationFrame(() => requestAnimationFrame(r)));
  measure();
  buildGhosts();
  buildQcCard();
  window.seek = seek;
  seek(0);
  window.STAGE_READY = true;

  // manual preview: stage/index.html?play=1
  if (new URLSearchParams(location.search).get('play')) {
    const t0 = performance.now();
    (function loop() {
      seek(((performance.now() - t0) / 1000) % TL.duration);
      requestAnimationFrame(loop);
    })();
  }
}

init();
