"""旁白稿生成器：M/narration.zh.md / M/narration.en.md（CONTRACT §77 拟；QA 面 §58）。

旁白与分镜同源（`shots.json`）——一个镜头一段词，配音（tts.py）与字幕（srt.py）读的是同一份文字，
三处永不各说各话（防腐第 9 条）。
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import shots as shots_mod  # noqa: E402

HEAD = {
    "zh": "（本稿由 `scripts/media/narration.py` 从 `scripts/media/shots.json` 生成，勿手改。一个镜头一段，配音与字幕用的是同一段文字。）",
    "en": "(Generated by `scripts/media/narration.py` from `scripts/media/shots.json` — do not hand-edit. One paragraph per shot; the voice-over and the subtitles use exactly this text.)",
}


def render(data: dict, lang: str) -> str:
    rows = shots_mod.timeline(data["shots"])
    title = data["title"][lang]
    lines = [f"# {title} — {'旁白（中文）' if lang == 'zh' else 'Narration (English)'}", "", HEAD[lang], ""]
    for i, row in enumerate(rows, start=1):
        shot = row["shot"]
        stamp = f"{row['start'] // 60:02d}:{row['start'] % 60:02d}"
        lines += [f"## {i}. `{shot['id']}` — {stamp} (+{shot['seconds']}s)", "", shot[lang], ""]
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="write narration.zh.md / narration.en.md")
    ap.add_argument("--outdir", required=True, help="M (artefact dir)")
    ap.add_argument("--shots", default=None)
    args = ap.parse_args(argv)
    data = shots_mod.load(args.shots)
    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    for lang in ("zh", "en"):
        path = outdir / f"narration.{lang}.md"
        path.write_text(render(data, lang), encoding="utf-8")
        print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
